### PR TITLE
Option for starting path

### PR DESCRIPTION
**Pull request by ChrisPenner**
## Overview

One half of https://github.com/unisonweb/unison/issues/3397 ; 
This will be more helpful after #3391  is merged since you won't need to wait for everything to load before being productive.

We should likely also look at storing the "last active path" somewhere and load that if no path is specified, but this doesn't do that yet.

## Implementation notes

* Adds a new CLI option for `starting path`. Unfortunately, due to how we have our CLI commands structured, it shows up as a global option even though it only works with `launch`. We may want to look into some sorta patch for optparse-applicative for this at some point. I made an issue [here](https://github.com/pcapriotti/optparse-applicative/issues/461)
* Adds `subparserInline` just because I learned about it when reading some issues; https://github.com/pcapriotti/optparse-applicative/issues/433 ; should avoid possible foot-guns in the future; apparently it's only not the default for backwards compat.

## Loose ends

* We should consider storing the last active path somewhere and load that if no path is specified.

- - -
This change is [Reviewable](https://reviewable.io/reviews/unisonweb/unison/3430)

### CODE REVIEW

**Comment by aryairani** [comment]
Should we have `launch` as an explicit command, and have the option relative to only that command — assuming there's some way to make launch the default command if none is specified?

**Comment by ChrisPenner** [comment]
@aryairani  I opened an issue regarding the problem here: https://github.com/pcapriotti/optparse-applicative/issues/461#issuecomment-1255656466

I'll try out some of the suggested workarounds and see if any of them end up in a reasonable state 😄

**Review by aryairani — APPROVED** [review]
Maybe want to try `noGlobal` per https://github.com/pcapriotti/optparse-applicative/issues/461#issuecomment-1255656466

**Comment by ChrisPenner** [comment]
The `noGlobal` option seems to have worked 👍🏼

**Pull request merged**
