### PR TITLE
Print custom error message in case of an empty watch expression

### PR DESCRIPTION
**Pull request by BenFradet**
c.f. #425

What's the best way to go about unit testing? Should I add to https://github.com/unisonweb/unison/blob/master/parser-typechecker/tests/Unison/Test/FileParser.hs ?

### CODE REVIEW

**Comment by pchiusano** [comment]
@BenFradet looks good am going to merge!

At the moment, we don't have a good way of testing error messages. I'd like to avoid having tests that depend on the exact formatting or wording of messages since I think that'll be too fragile.

I think it would be doable to have a little test harness that lets you compare the failing parse value, so something like:

``` Haskell
import EasyTest
expectFileParseFailure :: String -> (Parser.Error -> Test ()) -> Test ()
```

Which you then use to construct a bunch of tests, just making sure that the right kind of error makes its way into the parse error.

**Comment by BenFradet** [comment]
Thanks, I'll look into it.

**Comment by aryairani** [comment]
Hey @BenFradet — we need, but don't yet have, a test harness for CLI workflow.

It is meant to be something like:  send some `Input` to the Actions.hs loop, and then interpret the resulting `Free (Command i v) a` in the test harness to make sure it produces your anticipated `Notify` command.

**Comment by aryairani** [comment]
Oh, I'm late to the party.  That's another way.

**Comment by pchiusano** [comment]
@aryairani 😀yeah I think what I suggested is probably better if the goal is just to unit test the errors that the parser generates. If it's more of an integration test of how parser interacts with CLI and codebase state, then what you said. 😀

**Pull request merged**
