### PR TITLE
Implement Murmurhash in racket

### PR DESCRIPTION
**Pull request by jaredly**
There are probably some perf optimizations that could be done if we need it.

### CODE REVIEW

**Review by dolio — APPROVED** [review]
Looks fine to me.

**Review by pchiusano — APPROVED** [review]
Nice. @dolio do you want to add to this PR the integration with the runtime? Or do you think we should merge as is and then do the integration with a separate PR?

**Comment by dolio** [comment]
I'm just going to merge this, because I think the only associated change for the rest of the integration is going to be bumping the share code version.

**Comment by dolio** [comment]
BTW, while I was hooking this up, I was a little skeptical of the implementation, because it turns every value into bytes, and hashes individual bytes. However, it actually matches what we do in Haskell, apparently. We're just using the `ByteString` instance after converting to bytes, and that's how it behaves, rather than using 64bit chunks.

**Pull request merged**
