### PR TITLE
Merge newest trunk in "Upgrade to LTS 22.26 GHC 9.6.5"

### PR DESCRIPTION
**Pull request by neduard**
## Overview

Due to how github displays changes, this PR shows like it contains more changes that it actually has.  It shows all the new `trunk` changes since we're merging into an older branch.  The actual changes are tiny (and you can see at the end of the commit list):

* Merge newest trunk & resolve conflicts 6ed06f3
* Adds a missing `Functor` derives 456b8e6
* update transcripts (unsure why that's necessary) 4e44b94

Note: We can also to merge this directly into trunk if people are happy with it.

## Loose ends

1. As mentioned, not sure why the transcripts had to be updated

2. Although the CI tests pass, I had a [previous PR ](https://github.com/neduard/unison/pull/3) in which CI was failing after the above changes: https://github.com/neduard/unison/actions/runs/9918850847/job/27404234514 

As such, I had to make two additional changes:

* [replace .> with scratch/main> for the jit-setup transcript in the ci.yaml](https://github.com/neduard/unison/pull/3/commits/a4c9ee1dc3cc4910a64049631ab3a3e919e07416)
* [update jit-tests.output.md](https://github.com/neduard/unison/pull/3/commits/83c82027214aa5c88a845d635c0472b64bbc782b)

I think the tests now pass because we're caching the jit tests?

image

### CODE REVIEW

**Comment by ChrisPenner** [comment]
I swapped the merge target to trunk which makes it much easier to review, I think if we just merge this one it should automatically close #5142 and sort everything out 👍🏼 

View just the new changes here: https://github.com/unisonweb/unison/pull/5224/files/ecf5fe1df7e16c17f065fdf8544427ed56d69449..4e44b94ad63496657300d05a37a784445adb1094

**Review by ChrisPenner — APPROVED** [review]

**Comment by aryairani** [comment]
We're only supposed to use cached jit results when they would be the same anyway, but it's been hard to get right, so perhaps there's something wrong with the caching.

Do you think something had passed when it should have failed, or do you think it's currently passing when it should be failing?

**Comment by sellout** [comment]
>     * update transcripts (unsure why that's necessary) [4e44b94](https://github.com/unisonweb/unison/commit/4e44b94ad63496657300d05a37a784445adb1094)

This passes CI, so I suppose it’s ok, but I think the solver pulled a new version of cmark, which is now used for transcript parsing/printing.

cmark-hs 0.6.1 (released July 8 and called 0.7 in the changelog?) [upgrades from libcmark 0.29.0 to 0.30.3](https://hackage.haskell.org/package/cmark-0.6.1/changelog) and libcmark 0.30.0 (within that range) now [outputs all code blocks as fenced](https://github.com/commonmark/cmark/blob/3ec91f25de4a39fbac39e1f1068e0994392015c0/changelog.txt#L254).

I’m surprised the Stack grabbed the newer release – I thought we would have had to upgrade to LTS 22.27 (or something) to get cmark-hs 0.6.1. But I guess not. I suppose Stackage bumps minor releases in its snapshots?

**Comment by neduard** [comment]
> Do you think something had passed when it should have failed, or do you think it's currently passing when it should be failing?

It's currently passing when it should be failing.  I've raised  #5236 to highlight the issue & offer a potential fix/workaround but I'm not sure how good of a fix it is.  Let me know your thoughts!

**Pull request merged**
