### PR TITLE
Fix #1131 : Add windows Ctrl+C handling

### LINKED ISSUE #1131: Add Windows compliant ctrl+c handling
#912 added Unix compliant ctrl c handling in ucm. Discussion there called for a followup to add Windows compatibility. See [ghci](https://gitlab.haskell.org/ghc/ghc/blob/581cbc28e143a4ed8e7f794ed1618161222a5646/libraries/ghci/GHCi/Signals.hs#L35-L46) for an example.

### PR DESCRIPTION
**Pull request by sharno**
Add windows Ctrl+C handling
Fixes #1131 

The test for this maybe adding a windows target in CI?
But there are other issues in #598 and tests that don't pass yet

### CODE REVIEW

**Comment by sharno** [comment]
Now I'm not sure actually if this completely works, I was investigating the other problem with the file watcher yesterday and pressing Ctrl+C seems to leave the unison process running in the background. I'll need to look at this again soon

**Comment by sharno** [comment]
Oh I see what's happening now. This code is working fine and doing what it's supposed to do.

It's just [the handler of `UserInterrupt`](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/CommandLine/Main.hs#L233) is not quitting `unison.exe` if there's commands running (that could be a separate issue)

**Comment by pchiusano** [comment]
Great, thanks! Merging now.

If you want to work on figuring out how to get CI to do windows build that would be a most welcome PR, but can be separate from this one.

**Comment by aryairani** [comment]
This PR unfortunately apparently breaks the build for macOS; we should get that into CI as well.

**Comment by aryairani** [comment]
```
unison-parser-typechecker> Building executable 'unison' for unison-parser-typechecker-0.1..
unison-parser-typechecker> 
unison-parser-typechecker> /Users/arya/unison/master/parser-typechecker/<built-in>:15:10: error:
unison-parser-typechecker>      error: non-portable path to file '".stack-work/dist/x86_64-osx/Cabal-3.0.1.0/build/Unison/autogen/cabal_macros.h"'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
unison-parser-typechecker> #include ".stack-work/dist/x86_64-osx/Cabal-3.0.1.0/build/unison/autogen/cabal_macros.h"
unison-parser-typechecker>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unison-parser-typechecker>          ".stack-work/dist/x86_64-osx/Cabal-3.0.1.0/build/Unison/autogen/cabal_macros.h"
unison-parser-typechecker> 1 error generated.
unison-parser-typechecker> 
unison-parser-typechecker> /Users/arya/unison/master/parser-typechecker/unison/Main.hs:1:1: error:
unison-parser-typechecker>     `gcc' failed in phase `C pre-processor'. (Exit code: 1)
unison-parser-typechecker>   |
unison-parser-typechecker> 1 | {-# Language OverloadedStrings #-}
unison-parser-typechecker>   | ^
unison-parser-typechecker> 
```

**Comment by aryairani** [comment]
@sharno Would you mind re-creating this PR on top of the `osx-ci` branch?

**Comment by aryairani** [comment]
(No rush though, while #598 is still true, etc.)

**Pull request merged**
