### PR TITLE
Revert "Is Codebase.makeSelfContained' unnecessary?"

### PR DESCRIPTION
**Pull request by aryairani**
Reverts unisonweb/unison#771

@TomasMikula If you have a chance, could you take a look at #873 in terms of a test that fails without `makeSelfContained'`

### CODE REVIEW

**Comment by TomasMikula** [comment]
Such test would be nice and would definitely save us both some time. I don't know where to start, though - it is not just another test of a kind that's already in the codebase.

Btw, I have a much simpler version of `Var` that is not burdened by the implementation details of the runtime (namely `RefNamed` variables) or type inference (namely `Inference` variables). Removing `makeSelfContained'` was just an attempt to avoid having to modify it so that it does not use `RefNamed` vars. I will have to find a workaround (as I did for other uses of `RefNamed`).

**Comment by aryairani** [comment]
I went ahead and created a transcript test (#873, #816) for it.

**Comment by TomasMikula** [comment]
Nice! I was imagining some tricky programmatic way of initializing a codebase that would then be used for typechecking the term.

**Comment by aryairani** [comment]
@TomasMikula Yeah transcript tests are a big help. 

BTW, I’m all for simplifying and disentangling the current implementation, and appreciate your fresh perspective.

**Pull request merged**
