### PR TITLE
Delete travis build

### PR DESCRIPTION
**Pull request by pchiusano**
In favor of new GitHub actions build that @mitchellwrosen added in #1751 

Let's eyeball the CI results before merging.

### CODE REVIEW

**Comment by pchiusano** [comment]
Initial build has it downloading GHC... hoping that is a one-time thing.

**Comment by mitchellwrosen** [comment]
Yeah, it will be a one-time thing. It's because of this cache miss
Screen Shot 2020-11-24 at 4 37 48 PM

**Comment by pchiusano** [comment]
@mitchellwrosen any idea what the new `.mergify.yml` should look like? Specifically I'm not sure what to replace the travis thing with.

**Comment by pchiusano** [comment]
It is currently:

```
   conditions:
        - status-success=continuous-integration/travis-ci/pr  # what should this line be instead?
        - label=ready-to-merge
        - "#approved-reviews-by>=1"
```

**Comment by pchiusano** [comment]
Finished in 3 minutes, wowzers!

image

**Review by aryairani — APPROVED** [review]
test

**Pull request merged**
