### PR TITLE
Add TCP primops to racket

### PR DESCRIPTION
**Pull request by jaredly**
enough to connect to example.com!
I tried to add a test for "failure", but the `handle` plumbing doesn't seem to be all there -- it somehow swallowed the error.

### CODE REVIEW

**Comment by dolio** [comment]
Should the `TODO` test be uncommented? Is the problem just that the thing in the handle is delayed like you mentioned yesterday?

**Comment by jaredly** [comment]
oh lol forgot to push

**Comment by jaredly** [comment]
Ok @dolio I think this is ready to go!

**Review by dolio — APPROVED** [review]
Okay, looks good.

**Pull request merged**
