### PR TITLE
`add` individual definitions from .u file -- needs review

### PR DESCRIPTION
**Pull request by aryairani**
This PR enables you to add specific definitions from a .u file.  If your selection would be missing dependencies, it gets user confirmation before expanding the selection to include those dependencies.

Unfortunately, I think there were some unhandled cases with this PR, which I don't remember how to reproduce. 😅

Could someone help me stress test it before we merge?

```
master> 
  
  ┌
  │  ✅
  │  
  │  I found and typechecked these definitions in /Users/arya/unison/unison-src/Map.u:
  │  
  │    type Map k v
  │    Map.empty : Map k v
  │    Map.fromSequence : [(k, v)] -> Map k v
  │    Map.insert : k -> v -> Map k v -> Map k v
  │    Map.intersect : Map k v -> Map k v -> Map k v
  │    Map.intersectWith : (v -> v -> v2) -> Map k v -> Map k v -> Map k v2
  │    Map.keys : Map k v -> [k]
  │    Map.lookup : k -> Map k v -> Optional v
  │    Map.map : (v -> v2) -> Map k v -> Map k v2
  │    Map.singleton : k -> v -> Map k v
  │    Map.toSequence : Map k v -> [(k, v)]
  │    Map.union : Map k v -> Map k v -> Map k v
  │    Map.unionWith : (v -> v -> v) -> Map k v -> Map k v -> Map k v
  │    Map.values : Map k v -> [v]
  │    Search.exact : (Nat -> Int) -> Nat -> Nat -> Optional Nat
  │    Search.indexOf : a -> [a] -> Optional Nat
  │    Search.lub : (Nat -> Int) -> Nat -> Nat -> Nat
  │    Search.lubIndexOf : a -> [a] -> Nat
  │    Search.lubIndexOf' : a -> Nat -> [a] -> Nat
  │    Sequence.insert : Nat -> a -> [a] -> [a]
  │    Sequence.map : (a -> b) -> [a] -> [b]
  │    Sequence.replace : Nat -> a -> [a] -> [a]
  │    Sequence.slice : Nat -> Nat -> [a] -> [a]
  │    Sequence.unsafeAt : Nat -> [a] -> a
  │    Sequence.zip : [a] -> [b] -> [(a, b)]
  │    ex : [Nat]
  │    ex2 : [Nat]
  │    ex3 : [Nat]
  │  
  │  Now evaluating any watch expressions (lines starting with `>`)...
  └

master> add Map.intersectWith

  ┌
  │  ⚠️
  │  
  │  I would need to add all of these dependencies:
  │    type Map k v
  │    Map.intersectWith : (v -> v -> v2) -> Map k v -> Map k v -> Map k v2
  │    Search.lub : (Nat -> Int) -> Nat -> Nat -> Nat
  │    Search.lubIndexOf' : a -> Nat -> [a] -> Nat
  │    Sequence.unsafeAt : Nat -> [a] -> a
  │  
  │  Please repeat the same command to confirm the transitive additions.
  └

master> add Map.intersectWith

  ┌
  │  ✅
  │  
  │  I added these definitions:
  │  
  │    type Map
  │    Map.intersectWith  : (v -> v -> v2) -> Map k v -> Map k v -> Map k v2
  │    Search.lub         : (Nat -> Int) -> Nat -> Nat -> Nat
  │    Search.lubIndexOf' : a -> Nat -> [a] -> Nat
  │    Sequence.unsafeAt  : Nat -> [a] -> a
  └

master> 
```

### CODE REVIEW

**Comment by aryairani** [comment]
After we're happy with the feature, I need to remove `Debug.Trace` too.

**Comment by aryairani** [comment]
* [ ] Add tab-completion for definitions in the .u file?
* [ ] Fix crash when some dependents from file already added?

**Comment by pchiusano** [comment]
```
x = 1
y = x + 1
```

```
woot2> add x

  ┌
  │  ✅
  │  
  │  I added these definitions:
  │  
  │    x : Nat
  └

woot2> add y
fromList [#2WJfx]
fromList [#2WJfx,#4954N]
fromList [##Nat,##Nat.+,#2WJfx,#4954N]

  ┌
  │  ⚠️
  │  
  │  I would need to add all of these dependencies:
  │    y : Nat
  │  
  │  Please repeat the same command to confirm the transitive additions.
  └

woot2> add y
fromList [#2WJfx]
fromList [#2WJfx,#4954N]
fromList [##Nat,##Nat.+,#2WJfx,#4954N]
unison: can't hashComponents if bindings have free variables:
  ["x"]
  ["y"]
CallStack (from HasCallStack):
  error, called at src/Unison/ABT.hs:504:11 in unison-parser-typechecker-0.1-5VE78r8KW62FQY17lM27B6:Unison.ABT
```

We thought it was due to filtering out the `UnisonFile` too early (before hashing). Maybe just do the filtering after hashing? Could also maybe filter the `Branch0` before appending it to the `Branch`? (Also should avoid doing the `putTerm`,`putTypeDeclaration` for things that aren't selected..)

**Comment by pchiusano** [comment]
@aryairani I'd like to merge this, even if the output could be improved, just so it doesn't fall too far behind and get lost. Can you update to merge cleanly against current master?

**Comment by pchiusano** [comment]
This got reimplemented in wip/branchless

**Pull request closed without merging**
