### PR TITLE
add `debug.history` command to help render branch history

### PR DESCRIPTION
**Pull request by aryairani**
Sample output:
image

### CODE REVIEW

**Comment by pchiusano** [comment]
Wow, super cool @aryairani! How is this done? And what's with the Travis failures?

**Comment by aryairani** [comment]
I dunno what's up with Travis, it couldn't check out the code.  Conventional wisdom is: close and reopen the PR to retrigger Travis.

**Comment by aryairani** [comment]
It works by generating output in the format that's expected by this tool: http://bit-booster.com/graph.html You copy/paste the results there to get the graph.

**Comment by pchiusano** [comment]
Cool. Would be nice to have a direct way of outputting something to svg without having to go through this random website. But this is cool for now to help with debugging.

**Comment by aryairani** [comment]
💯

**Pull request merged**
