### PR TITLE
Adding set echo io bindings

### PR DESCRIPTION
**Pull request by unorsk**
Adding bindings for `setEcho`, `getEcho`, `ready` and `getChar`

## Overview

These functions are very handy when working with a terminal and seem to be missing in unison. 
Basically `setEcho` turns echoing on/off when reading characters from a terminal.

## Implementation notes

The implementation is straightforward – just a couple of binding declarations for new functions in unison, that would be calling underlaying Haskell functions such as `hSetEcho`, `hGetEcho` and etc.

## Interesting/controversial decisions

None :)

## Test coverage

I haven't included any tests, should I? :)

- - -
This change is [Reviewable](https://reviewable.io/reviews/unisonweb/unison/3476)

### CODE REVIEW

**Comment by dolio** [comment]
I think the changes look good.

Your CI failures are caused by transcript changes caused by the new builtins. Can you run `cabal run transcripts` or the `stack` equivalent (not sure if it's `run` or `exec`) and commit the updated outputs?

**Comment by unorsk** [comment]
> I think the changes look good.
> 
> Your CI failures are caused by transcript changes caused by the new builtins. Can you run `cabal run transcripts` or the `stack` equivalent (not sure if it's `run` or `exec`) and commit the updated outputs?

@dolio, Done! :)

**Comment by aryairani** [comment]
> I haven't included any tests, should I? :)

Maybe some evidence of manual testing, like a demo video? 🙏

**Comment by unorsk** [comment]
@aryairani sure!

```
echoTest : '{IO, Exception} ()
echoTest = do
  use Text ++
  setBuffering stdIn NoBuffering
  setEcho stdIn false
  c = getChar stdIn
  setEcho stdIn true
  putText stdOut ("You pressed: '" ++ Char.toText c ++ "'")
```

testecho

**Review by dolio — APPROVED** [review]
Looks fine to me.

**Comment by ceedubs** [comment]
@unorsk thank you this is great!

**Comment by aryairani** [comment]
Thanks @unorsk!

**Pull request merged**
