### PR TITLE
Group test results by definition

### PR DESCRIPTION
**Pull request by sellout**
## Overview

Avoids duplication in the output.

Follow-up to #5140.

## Interesting/controversial decisions

With this new display, I’m wondering if it makes sense to _not_ split the failures from the successes, so all the terns for a definition are together rather than having the definition duplicated in each list.

## Test coverage

This is reflected in a number of transcripts.

### CODE REVIEW

**Comment by sellout** [comment]
So, what do you think about moving to
```ucm
  Cached test results (`help testcache` to learn more)
  
    1. fix5080.tests  ◉ got the right answer
                      ✗ [1, 2, 3]
   
   🚫 1 test(s) failing, ✅ 1 test(s) passing
```
instead of
```ucm
  Cached test results (`help testcache` to learn more)
  
    1. fix5080.tests  ◉ got the right answer

    2. fix5080.tests  ✗ [1, 2, 3]
   
   🚫 1 test(s) failing, ✅ 1 test(s) passing
```

**Comment by ceedubs** [comment]
Nice!

@sellout I agree that for the small example, not printing the successes and failures separately looks better. But I do think that there is some benefit in putting all of the failures at the top or bottom so it's easy to find them if you have a bunch of tests run. No super strong opinions, though.

**Review by ceedubs — APPROVED** [review]

**Comment by sellout** [comment]
> I agree that for the small example, not printing the successes and failures separately looks better. But I do think that there is some benefit in putting all of the failures at the top or bottom so it's easy to find them if you have a bunch of tests run.

Yeah, it can be nice to have the failures all together at the end. The output is also colorized, though, so it does make scanning a long list for failures pretty easy.

Regardless, it can stay the way it is for now, and it’s easy enough to change later if we want.

**Comment by ceedubs** [comment]
Just gave this a try and it's working great!

**Pull request merged**
