### PR TITLE
Allow providing scratch file path

### PR DESCRIPTION
**Pull request by francisdb**
Allows setting the scratch file path to something else than `.`
Instead of `-haskell` you will have to use `--haskell`

Question: Is that `_scratchFilePath` / `_initialFilePath` something that will be added in the future as it is currently not used? Otherwise I can remove that part of the code

see also #339

### CODE REVIEW

**Comment by pchiusano** [comment]
@francisdb can you explain this one a bit more? Maybe post an example session of how the `unison` executable can be launched after this change? (Also, what do you see if you do something incorrectly when launching `unison` exe)

**Comment by francisdb** [comment]
See the related ticket, wanted to have external sources and symlinks did not work so needed option to change the scratch path

**Comment by pchiusano** [comment]
@francisdb cool, can you just show the usage of it, like what do I type at the command line to make use of this new functionality, and what is the output I see? :)

**Comment by francisdb** [comment]
Check out https://github.com/francisdb/unison-json and then run this, it only changes the scratch path, nothing more

```
stack exec unison -- -s ../unison-json/src
```

Now what remains is running tests, something like this?

```
stack exec unison -- test -s ../unison-json/src

[test output here]
```

Full output below

```
stack exec unison -- -s ../unison-json/src
...

  ┌
  │  ✅
  │
  │  I found and typechecked these definitions in /Users/francisdb/workspace/unison-json/src/json.u:
  │
  │    type Either a b
  │    type Json.Value
  │    type Token
  │    Json.format : Json.Value -> Text
  │    Json.format : Json.Value -> Text
  │    Json.lex : Text -> [Token]
  │    Json.parse : Text -> Optional Json.Value
  │    Sequence.flatMap : (a -> [a]) -> [a] -> [a]
  │    Sequence.fold : a -> (a -> a -> a) -> [a] -> a
  │    Sequence.intersperse : a -> [a] -> [a]
  │    Sequence.map : (a -> b) -> [a] -> [b]
  │    Sequence.prependToAll : a -> [a] -> [a]
  │    Text.concat : [Text] -> Text
  │    Text.concatSeq : Text -> Text -> Text -> [Text] -> Text
  │    formatProp : (Text, Json.Value) -> Text
  │    formatProp : (Text, Json.Value) -> Text
  │    lexString : Text -> Either Text (Text, Text)
  │
  │  Now evaluating any watch expressions (lines starting with `>`) ...
  └

  ┌
  │  131 | > Json.format (Json.Value.Object [("foo", Json.Value.Number "123"), ("bar", Json.Value.Array [Json.Value.Null, Json.Value.String "test"])])
  │          ⧩
  │          "{\"foo\":123,\"bar\":[null,\"test\"]}"
  └
  ┌
  │  133 | > Json.lex "\"test\""
  │          ⧩
  │          Con #5cbWz9X1yckJnAbgh5HMxCAWwB9otVmzy6km1BE5gQ1KscRk9ZZZrD55tSXZzm2qWreQV6FsX5DkpmyCiAFei3La 1
  │            ("test", "")
  └
  ┌
  │  135 | > Json.lex "\"test"
  │          ⧩
  │          Con #5cbWz9X1yckJnAbgh5HMxCAWwB9otVmzy6km1BE5gQ1KscRk9ZZZrD55tSXZzm2qWreQV6FsX5DkpmyCiAFei3La 0
  │            "Missing closing\""
  └
  ┌
  │  137 | > Json.lex "[]"
  │          ⧩
  │          [ Con #2pPZi4FuaByP6hms9vHr2DYG37ZUgoDFixMDXryCC5Y3ZFKBjRi5x5PUiqkmJqau2ZxnpHNBAaHTpHWLZC1FDb1k 0
  │            "[",
  │           Con #2pPZi4FuaByP6hms9vHr2DYG37ZUgoDFixMDXryCC5Y3ZFKBjRi5x5PUiqkmJqau2ZxnpHNBAaHTpHWLZC1FDb1k 0
  │            "]"]
  └
  ┌
  │  139 | > Json.lex "{\"foo\":123,\"bar\":[null,\"test\"]}"
  │          ⧩
  │          Con #5cbWz9X1yckJnAbgh5HMxCAWwB9otVmzy6km1BE5gQ1KscRk9ZZZrD55tSXZzm2qWreQV6FsX5DkpmyCiAFei3La 1
  │            ("foo", ":123,\"bar\":[null,\"test\"]}")
  └
  ┌
  │  141 | > case (Json.parse "{'foo':123,'bar':[null,'test']}") of Some a -> format a
  │          ⧩
  │          "\"TODO\""
  └

```

**Comment by francisdb** [comment]
unison can be run in any path with the new hasell runtime so no need for this any more

**Pull request closed without merging**
