### PR TITLE
Add 'delete' command

### LINKED ISSUE #662: should I really have to specify delete.term vs delete.type?
I have to write `delete.term` or `delete.type` according to what I'm trying to delete.  But should I really have to, in the common case where the name does not exist both as term and type, but only as one of the two?

Ditto `alias` and `move`.

I appreciate it's hard to get too excited about this one.

(`delete` and `move` have the patch and namespace variants to think about as well.)

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This patch adds `delete`, which sort of combines `delete.term` and `delete.type`. If there are any ambiguities, it bails. Transcript test included!

Fixes #662

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
I would hope so! (Pretty sure I did not regress here... double checking)

**Comment by mitchellwrosen** [comment]
Yeah, nope, `delete` just doesn't give feedback yet.

**Comment by aryairani** [comment]
Ok well then FF to merge if you’re ready. :)

**Comment by pchiusano** [comment]
Nice! I like the transcript test.

**Pull request merged**
