### PR TITLE
Make Term and Type not depend on TypeVar

### PR DESCRIPTION
**Pull request by TomasMikula**
`TypeVar` is just an auxiliary data type for typechecking. `Term` and `Type` should not depend on it.

Also, move it to the `Typechecker` module.

### CODE REVIEW

**Comment by TomasMikula** [comment]
After resolving conflicts, this now moves `TypeVar` back to `parser-typechecker` package.

**Comment by TomasMikula** [comment]
Don't know why GitHub hasn't picked up the result from Travis.

**Comment by pchiusano** [comment]
This looks good, I’m going to try closing and reopening to kickstart Travis (anyone know a better way to achieve that?).

**Comment by pchiusano** [comment]
Great, thanks, merging.

**Pull request merged**
