### PR TITLE
remove some dead parser code

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This patch deleted a bunch of unused code in various parser modules... not sure if you want to keep any of it around, but anyways, it's all unused at the moment :)

### CODE REVIEW

**Comment by aryairani** [comment]
Make sure to build/run tests before PR :)

**Comment by seagreen** [comment]
Btw @mitchellwrosen if you don't care who does it I can take this one up.

**Comment by mitchellwrosen** [comment]
Go for it @seagreen!

**Comment by mitchellwrosen** [comment]
Moved to #1024

**Pull request closed without merging**
