### PR TITLE
make the "latest" prerelease contain both arches like the tagged rele…

### PR DESCRIPTION
**Pull request by stew**
This uses what we learned yesterday about GHA in order to make the automated `latest` releases be multi-arch like our tagged releases

### CODE REVIEW

**Review by pchiusano — APPROVED** [review]

**Comment by pchiusano** [comment]
@aryairani might have more of an opinion on this one

**Comment by aryairani** [comment]
Sounds great!

**Review by aryairani — APPROVED** [review]
Sounds great!  Let me know if the filenames change though, and I'll update the homebrew formula.

**Comment by aryairani** [comment]
@stew Is it ready to merge?

**Pull request merged**
