### PR TITLE
Force line breaks between rows in wrapColumn2

### LINKED ISSUE #820: pretty-printing glitch in wrapColumn2?
image

I believe this 👇 should produce 3 lines of output, but it only produces 2? ☝️ 
```
  (P.wrapColumn2
    [ ("`list`", "lists definitions and namespaces at the current level of the current namespace.")
    , ( "`list foo`", "lists the 'foo' namespace." )
    , ( "`list .foo`", "lists the '.foo' namespace." )
    ]
  )
```

Change my mind! :)

### PR DESCRIPTION
**Pull request by jdevuyst**
This fixes #820

### CODE REVIEW

**Comment by jdevuyst** [comment]
Oops. I didn't notice the test failures. They don't show up when I run `stack run test` or `stack test` in the root directory.

**Comment by atacratic** [comment]
Could you try `stack exec test`? That's what I type. Let us know!

Shout if you need a hand with the TermPrinter. I think some of the existing behaviour that your change alters is a bit janky. But I think you do need to change the TermPrinter somewhere.

**Comment by jdevuyst** [comment]
`stack exec tests` indeed does the trick.

I updated my PR, which now passes all tests. Not sure if it's the solution you'd want though.

The gist of my patch is that I'm wrapping the lines in an `Append` as this leads to a 'go Right' in `render`, meaning `flow` is not called for the newlines that separate rows.

**Comment by atacratic** [comment]
(`stack run test` seems to be running the tests for yaks/easytest, but I can't work out why.)

Tagging @aryairani for a review and merge?

**Comment by aryairani** [comment]
@atacratic That’s probably just the command to run stack tests for all subprojects, but we want `stack exec tests` not `stack run test`, right
?
@jdevuyst Would you include the new output for the help command, mirroring the buggy output of  #820?

**Comment by jdevuyst** [comment]
Screen Shot 2019-10-13 at 21 47 59

**Pull request merged**
