### PR TITLE
Mutators gonna mutate

### PR DESCRIPTION
**Pull request by runarorama**

### CODE REVIEW

**Comment by aryairani** [comment]
Also, awesome!

**Comment by pchiusano** [comment]
Ok think am starting to get this... rather than patterns taking in their RHS (and doing some pushing before calling their RHS), patterns just mutate the Result object with variables they’ve captured. Compilation of each case then runs the pattern, extracts the bound variables from the Result, and then calls the RHS.

**Comment by aryairani** [comment]
Oh, I see now where it returns U.

**Comment by pchiusano** [comment]
I think might have a nice simplification to this basic idea, will explain!

**Pull request merged**
