### PR TITLE
Remove UCM globbing as a feature

### PR DESCRIPTION
**Pull request by ChrisPenner**
## Overview

Does anyone really use globbing now that `fzf` works on most commands?
If yes, speak now.

Globbing currently doesn't seem to solve any real problems,  especially since recursive globs don't exist. It seems `fzf` solves most of  the use-cases globbing was meant for, so should we just delete the feature so we don't need to maintain it (and confuse anyone)?

## Implementation notes

Remove globbing

### CODE REVIEW

**Comment by ceedubs** [comment]
FWIW I don't really use UCM globs and I agree that the lack of recursive globs stifles their usefulness.

**Review by aryairani — APPROVED** [review]

**Comment by tankorsmash** [comment]
It's been a little while, but I thought you could do `view List.?` to view everything within `List` all at once. I'm not sure how to achieve this currently.

 Maybe this is better suited for the Discord, but I'm curious to know how to use fzf and `view` to avoid having to type `List.` every time I'm looking to view everything within List, all at once. Currently the closest I can get it is `view` and then `Shift-Tab` on every item there.

I'd love to have something like `view List.` and have it pre-populate the fzf list with `List.` for me, so that when I sit down to build something, I can quickly open up many related functions without necessarily remembering them all by name.

**Comment by pchiusano** [comment]
You could do find or find-in, which will give you a numbered list, then use ‘view 1-20’ to view a range of the results.

**Comment by tankorsmash** [comment]
Thank you, that helps! `find List.` lists a bunch of functions without fzf support, but it does let me open one at a time like you said.

I'm still looking for something closer to opening a file called `List.ml` and being able to view all the function implementations in my editor, since I can typically use my LSP to jump between definitions as quickly as I see them. The Unison LSP doesn't support that as far as I can tell, so there's a good bit of friction as I'm trying to explore my codebase. 

The Docs UI is gorgeous and likely best-in-class, but as a rabid vim user, I'd still like to remain in my editor and do as little typing as possible (and no mouse usage at all) to jump to different implementations.

**Comment by ceedubs** [comment]
You can do something like:

```
> ls lib.base_3_2_0.data.List
> view 1-1000
```

Or you can use `edit` instead of `view`. It's still not the most ergonomic since you have to fully-specify the path to `ls`. But it's not _so_ bad. I agree that it would be great to have better support for function discovery with LSP. You can get a little mileage out of the LSP autocomplete support, but it's not the best discovery mechanism.

I haven't tried it but you might also be able to set up a [select-all keybinding for fzf](https://github.com/junegunn/fzf/issues/257#issuecomment-110390003).

**Comment by tankorsmash** [comment]
Thank you both, I didn't know about passing the range of values. I'll look into making the keybindings. Thank you!

**Pull request merged**
