### PR TITLE
Fix division and modulus for Nat

### LINKED ISSUE #2225: Division on `Nat` is wrong for large numbers
The behaviour of the built-in DIVN (and probably MODN too) is incorrect.

``` unison
> maxNat / 2
```

This results in `maxNat` again, which is obviously wrong.

### PR DESCRIPTION
**Pull request by runarorama**
Fixes #2225

### CODE REVIEW

**Comment by aryairani** [comment]
Maybe a new or updated transcript, to show them working correctly?

**Comment by pchiusano** [comment]
@runarorama you can add a few quick tests in this file https://github.com/unisonweb/unison/blob/trunk/unison-src/transcripts-using-base/builtins.md#nat-functions should take you like 2 minutes.

**Review by dolio — APPROVED** [review]
Looks good to me.

**Comment by pchiusano** [comment]
Dammit. I shoulda removed ready-to-merge - I'd probably avoid adding that label before PR review unless you really think a PR is trivial and there's no chance of any discussion about it.

@runarorama I created https://github.com/unisonweb/unison/issues/2232 to track adding those tests.

**Pull request merged**
