### PR TITLE
Add `branch` command that creates a branch

### PR DESCRIPTION
**Pull request by mitchellwrosen**
## Overview

This PR adds a `branch <name>` command that creates a new branch from some existing contents.

Note: ultimately we want `branch` to be able to take two arguments: `branch <source> <name>`. This PR only implements the one-arg variant, `branch <name>`. To adjust `<source>`, you'll have to first `cd` or `switch` there.

Note: `branch` is intended to replace `switch`'s ability to create branches, but `switch` was not changed by this PR.

There are four ways a branch can be created:

1. From another branch in the same project.

    Screenshot from 2023-04-06 14-45-06
    
    The suggested wording for this output message from @pchiusano was:
    
    ```
    foo/main> branch feature1

    Created /feature1 branch based off /main.
  
    Tip: Use `merge /feature1 /main` to merge your work back into `/main` branch.
    ```
    
    However, before copying that in verbatim I wanted to get all four cases down on paper.
    
2. From another branch in some other project.

    Screenshot from 2023-04-06 14-45-43

3. From loose code.

    Screenshot from 2023-04-06 14-47-56

4. From nothingness (creating an empty branch). In the current trunk, you can accomplish this by `switch`ing into a new branch from outside the project. That feature is going to be deleted in favor of a `branch.empty` command, but we still need a wording for it before merging this PR.

    Screenshot from 2023-04-06 14-48-21

## Test coverage

Transcript incoming

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
This is ready for review, but the output messages in the screenshots above will of course need to change. That's also the source of the test errors in CI.

Any suggestions?

**Comment by pchiusano** [comment]
@mitchellwrosen -

> This is ready for review, but the output messages in the screenshots above will of course need to change. 

K, here's my suggestions for those cases.

**1**

```
Done. I've created the /feature1 branch based off /main.

Tip: Use `merge /feature1 /main` to merge your work back into /main branch.
```

**2**
```
Done. I've created the foobar/feature1 branch based off oink/main.
```

(don't show the tip about merging, since that doesn't make much sense here)

**3**

```
Done. I've created the foobar/feature1 branch from the namespace .some.loose.code.
```

(also don't show the tip about merging)

**4**

```
Done. I've created an empty branch foobar/topic4.

Tip: use `merge /somebranch` or `merge .path.to.code` to initialize this branch
```

CI is failing just due to transcript needing a refresh, looks like?

**Review by pchiusano — APPROVED** [review]
Left comments on message wording. LGTM! 

https://github.com/unisonweb/unison/pull/3904#issuecomment-1499658685

**Comment by pchiusano** [comment]
And yeah I'd add or augment an existing transcript to exercise.

**Pull request merged**
