### PR TITLE
Fix then/else not being able to start identifiers

### LINKED ISSUE #2727: Parser finds keywords a bit too eagerly, should operate over tokens instead
The following transcript fails:

    ```unison
    thenamespace = 1
    ```
    
     ```ucm
    .> add
    ```

With error:

    ⚙️   Processing stanza 2 of 3.# Empty namespace behaviours
    
    ```unison
    thenamespace = 1
    ```
    
    ```ucm
    
      I found a closing 'then' here without a matching 'if'.
    
          1 | thenamespace = 1
    
    
    ```

### PR DESCRIPTION
**Pull request by kanwren**
## Overview

Per #2727, some keywords could not appear at the start of an identifier, since the lexer would be too eager and lex a keyword. For example, `thenumber` should be a valid identifier, but since it starts with `then`, it would instead cause a parse error due to no matching `if`.

Specifically, this turned out to be only wordy keywords that closed blocks, and more specifically only `then` and `else` as written.

Resolves #2727

## Implementation notes

Previously, wordy keywords that closed blocks (in particular "then" and "else") were being lexed using `lit` in `close'`, rather than expecting to be followed by some wordy separator as in `openKw`. This ensures that `then` and `else` are not followed by wordy identifier characters before lexing them as keywords.

## Test coverage

Adds a test to ensure that `if`/`then`/`else` immediately followed by other legal wordy identifier characters will still lex as a single identifier.

### CODE REVIEW

**Comment by kanwren** [comment]
I will not rest until I have hunted down all of the parser-typechecker bugs that brought me here in the first place :p

**Review by pchiusano — CHANGES_REQUESTED** [review]
Thanks for knocking this out!!

The unit test is good, but I'd like to see an integration/regression test in the form of a transcript. It looks like there's already a test (fix2091.md) that ensures it's okay to start a term or type identifier with `type` or `ability`, but a similar test for all the keywords would be nice - I'd rename fix2091.md to like `keyword-identifiers.md` and then just add more examples in there that hit all the keywords, including `then` and `else`.

**Comment by kanwren** [comment]
I modified the aforementioned transcript. It now checks that all of the keywords (except `∀`) can start identifiers in term names and type names (including abilities) when the different types of wordy characters follow them. Let me know if it's overkill or needs more variety :sweat_smile:

**Comment by pchiusano** [comment]
Looks great! Thanks for adding the transcript.

FYI, you can do `unison:hide` on a stanza if you don't care to see the typechecking output in the transcript output. (Also you can do `ucm:hide` on a `ucm` stanza) It will still fail the transcript if the stanza triggers a failure. I might have used that here just to make the output look a little cleaner.

https://raw.githubusercontent.com/unisonweb/unison/trunk/unison-src/transcripts/hello.md has more details on the transcript format.

I'm going to leave this open till tomorrow in case you want to tweak that, but I also think it is perfectly fine as is.

**Review by pchiusano — APPROVED** [review]

**Review by ceedubs — APPROVED** [review]
Nice thank you @nprindle!

**Comment by kanwren** [comment]
@pchiusano Good point, thank you! I agree. I've hidden the output in the transcript.

**Comment by pchiusano** [comment]
👍 great, merging

**Pull request merged**
