### PR TITLE
Merge #1871 (delete old runtime) into wip/codebase2

### PR DESCRIPTION
**Pull request by mitchellwrosen**
To be merged after #1891

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
🤔 Hm, there shouldn't be 171 commits reachable by this commit but not wip/codebase2, now that #1891 was merged. Investigating...

**Comment by mitchellwrosen** [comment]
Just a GitHub caching issue, or something.

```
$ git rev-list wip/codebase2..delete-old-runtime-codebase2
14f03adbcc26fc4fadaf1f97b3fafd9e7199639d
4c57092398d80dc4c2e2c79d22f845c6b93c5024
7b43d6ada60bcb73402a1b0631cb64c06568719d
b4594fb48993f16f64708f0310dd2d22b4747dd0
ac5d1a005621df61a6d1c3d897876c3ffd5cf709
e59b8034b552313a10ca14dacdc2b54c435822ec
bc5cd858f8401cc35f2e684406e7f6ac8fa2691c
d8ba2c5503c8a368f21197cdbb7c499033e6fa1b
27156f7de30a388571d97fc4d0e0da2a27029da9
140cf696242003558985f4e15bcfe87c6070a2ba
7c0f8ac20bfb04bebcff163be82815419615a414
1804ab9d538fab97487652aebdad928b66af0ed3
e25e43edc98b7c0b253aefbd19907611cce70879
6019b02787ae7b29b9703132f8da83a047ee805c
90f3a0cc537b4e7206f5cfb0ad7c0b5087f7fa2d
a03d6cf5a634ec2ab856a9c87882d5d377bc575b
```

**Comment by aryairani** [comment]
Oops, I was too slow and created a conflict... let's see.

**Review by aryairani — APPROVED** [review]
Thanks!

**Comment by aryairani** [comment]
lol. mergify bot canceled itself when it removed the label?

**Pull request merged**
