### PR TITLE
bugfix: show `push` error messages

### LINKED ISSUE #4152: push fails with just ❗️ when authentication is required
The output is no longer in my terminal, but I did a `push` and it said something like:

```
uploaded 0 entities

❗️
```

I authenticated with `auth.login` and then a new push succeeded.

### PR DESCRIPTION
**Pull request by mitchellwrosen**
Fixes #4152 

Screen Shot 2024-06-10 at 10 44 15 AM

This PR fixes the bug in `push` that essentially caused error messages to flash briefly, then disappear.

The bug was caused by a bad interaction between our normal "output" mechanism (just putting to stdout) and our live-updating output mechanism (which prints "Uploaded N entities..." where N updates in-place).

The fix is to release the console region resource first, then inspect whether the upload failed and short-circuit with an error message if so, rather than short-circuit with an error message while holding on to the console region resource, because the resource sort of internally tracks how large it is, and so printing messages to stdout and then closing it is not really going to visually do the right thing.

### CODE REVIEW

**Comment by aryairani** [comment]
I want to start capturing all our messages in transcripts. Is there a way to do that for this one?

**Comment by mitchellwrosen** [comment]
@aryairani I don't think so, it hits the network, and our transcript tests don't have a sort of mock network layer

**Review by aryairani — APPROVED** [review]

**Comment by aryairani** [comment]
I think hitting the network is not a deal-breaker as long as we can get reasonably consistent results.
e.g. we already have transcripts that need to download `unison/base`.
But agree it doesn't make sense to try to capture every kind of network failure with transcripts.

**Comment by mitchellwrosen** [comment]
Oh, I didn't realize we already hit the network in transcripts. Which transcripts download `@unison/base`?

It would be easy to capture this output in a transcript – just try pushing to something that like `@unison/base/main` and get rejected. I just assumed we wouldn't want to hit the network in our test suite, because it seems like it could be a hinderance in a few ways.

**Comment by aryairani** [comment]
Looking at them, it's less clear than I remembered. There's `base.md`; and then there's also `_base.md`, which doesn't use the network, but maybe should?

**Comment by aryairani** [comment]
I also put some network access in `pull-errors.md` (relevant / analogous to this PR)

**Pull request merged**
