### PR TITLE
Report a minimal error on not finding a branch at remote path

### LINKED ISSUE #2473: UCM treats missing branches as empty when it should probably error
## Actual Behaviour

In UCM:

```
.> pull https://github.com/unisonweb/base:.missing .mymissing
  Importing downloaded files into local codebase...
  Done syncing 468 entities.

  Nothing changed as a result of the merge.


  😶

  .mymissing was already up-to-date with https://github.com/unisonweb/base:.missing.
```

UCM happily pretends that `.missing` is just an empty branch, which is probably not helpful in most cases, in particular when you accidentally typo, it will seem like everything succeeded.

This recently cost me and @rlmark a bit of our sanity with the automatic base-download feature, where there was a casing mismatch but it appeared as though everything was working as planned.

## Expected behaviour

UCM should print some sort of `branch not found on remote` error; and maybe even make spelling suggestions.

## How to start

Here's the spot where the branch is being fetched:

https://github.com/unisonweb/unison/blob/3996559579bf5a35bf885ecb4f7d5838574b027e/parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs#L1054

Perhaps switch to using `Branch.getAt` which returns a Maybe; then throw the appropriate error if it's a Nothing.

### PR DESCRIPTION
**Pull request by plumenator**
## Overview

Fixes #2473

### CODE REVIEW

**Comment by plumenator** [comment]
Will update the description later. Just a draft for now, we might handle spelling suggestions too.

**Comment by pchiusano** [comment]
Nice! Let us know if there's anything we can do to help out.

**Comment by pchiusano** [comment]
Ooops, definitely did not mean to close that.

**Review by ChrisPenner — APPROVED** [review]
Looks good to me! Anything else you were hoping to add?

**Comment by plumenator** [comment]
Sorry, I got caught up in life and work. If you approve, sure, let's ship it. I was hoping to add spelling suggestions, but I guess that can be a separate PR

**Comment by ChrisPenner** [comment]
This is great, I went ahead and merged, but realized you haven't added yourself to the Contributors file, so please feel free to add yourself in a new PR and we'll get that merged post-haste! Thanks!

**Comment by plumenator** [comment]
Done! #2556

**Pull request merged**
