### PR TITLE
Leveldb simplified

### PR DESCRIPTION
**Pull request by sfultong**
leveldb store

note that I set stack to use nix to resolve non-haskell dependencies. This should be fine to remove.

### CODE REVIEW

**Comment by NightRa** [comment]
Installing LevelDB on Windows is nearly impossible.
Using LevelDB for the project means limiting Unison to specific platforms for the foreseeable future.

**Comment by Ericson2314** [comment]
Make a canal flag to choose the back end? Also, I was having trouble booting ghcjs with stack in nix, so I'm curious what you did.

**Comment by pchiusano** [comment]
FYI, @NightRa I suggested that @sfultong look into LevelDB, so blame him, not me. :) 

@sfultong could you at least create a separate executable with the additional dependencies? That way others on Windows can still build the node. And then we can find a good solution for building on Windows - it would be fine if on Windows a totally different library were used. (edit: what @Ericson2314 [said above](https://github.com/unisonweb/unison/pull/43#issuecomment-210117494) sounds promising)

It would be nice if there were a pure-Haskell persistent key-value store (not in-memory). I was looking at https://hackage.haskell.org/package/keyvaluehash but it apparently does not free deleted old values. That would not really be a problem for the code store, but it would be a problem for the other uses I had in mind (like exposing a nice Unison API for persistent key-value stores).

**Comment by sfultong** [comment]
@Ericson2314 make sure stack is up to date in nix (I'm using the 15.09 profile), and check out https://github.com/sfultong/unison/commit/ce1c620efe1bc01feb2de8b5b2effa71f486ea48

**Comment by Ericson2314** [comment]
@sfultlong oh, stack can use nix-built ghcjs?!

**Comment by sfultong** [comment]
@Ericson2314 yeah, it's great. Check out http://stack.readthedocs.org/en/stable/nix_integration/

**Comment by sfultong** [comment]
Well, technically, it still builds the custom ghcjs that Paul specified in the stack.yaml. But all the non-haskell dependencies for doing so are resolved through nix.

You may have to set the environment variable TMPDIR to something like /tmp (ordinarily it's set to an in-memory filesystem, so it easily runs out of memory), and I forget why I had to turn off pure nix environments, but it didn't build until I did.

**Comment by Ericson2314** [comment]
Hmm I got 16 gigs, but I'll try that.

**Comment by sfultong** [comment]
@pchiusano  (cc @NightRa) - didn't you say that the leveldb bindings would be a prerequisite for the FFI? Oh wait, now when I read this back to myself, I realize you said "bindings", and I probably misunderstood that to mean you wanted it used for the store.

**Comment by pchiusano** [comment]
@sfultong yeah, I am more interested in just having a nice library for accessing a key-value store in Unison. Something like:

```Haskell
data Index k v

index : Remote! (Index k v)
lookup : k -> Index k v -> Remote! (Maybe v)
delete : k -> Index k v -> Remote! ()
-- keys : Index k v -> Stream Remote! k
```

That can be next. Let me review this PR first though.

The thing I was saying about FFI is that I'd like to have a better story for FFI than hardcoding external functions as 'builtins', which is what is done currently (you'll see how this works if you work on adding the API above).

FYI for anyone else reading this, @sfultong emailed me to ask about possible projects he could help with and I sent him some semi-incoherent quick thoughts.

**Comment by pchiusano** [comment]
Hey @sfultong sorry for very long delay in responding to this, I'll be focused on Unison for the foreseeable future so should be more responsive going forward. :) Can you use a _cabal flag_ at _build time_, not a runtime flag for this? And/or just have separate targets, `unison-node` and `unison-node-leveldb`, say, with different deps. That way we don't incur the dependency on leveldb for all of the node, and people who can't build level db can still run a node.

**Comment by sfultong** [comment]
@pchiusano  Ah, cabal flag. Sorry, that should have been obvious.

I'm not sure if this PR really has any value, but it seems like it's working at least.

**Comment by pchiusano** [comment]
Am merging this. I think it might be useful as it could have better performance than hitting the file system every time (though I'm guessing the disk cache makes up for some of that). 

Not sure what I want to do long term about a key-value store dependency. I want something embeddable, that works on all platforms. I guess I'd be okay if we needed two different libraries, one for *nix, one for Windows.

It would be awesome if there were a pure Haskell key-value store with features equivalent to LevelDB. If anyone would like to implement one, using [@ekmett's cache oblivious stuff](https://yow.eventer.com/yow-2014-1222/functionally-oblivious-and-succinct-by-edward-kmett-1701) that would be a very useful project for the Haskell ecosystem (it could live in a separate project from Unison).

**Pull request merged**
