### PR TITLE
Remove unused Language Pragmas

### PR DESCRIPTION
**Pull request by noahhaasis**
Remove all unused Language Pragmas found by hlint.

### CODE REVIEW

**Comment by aryairani** [comment]
I’m thinking a better fix would be putting most of the pragmas into the build file.  Thoughts?

**Comment by noahhaasis** [comment]
Would you add it for each executable separately or just to the library section?

**Comment by aryairani** [comment]
OverloadedStrings

**Comment by runarorama** [comment]
Merging this since it's a good change and self-contained.

**Pull request merged**
