### PR TITLE
Add Int.mod to builtinsSrc

### PR DESCRIPTION
**Pull request by mitchellwrosen**
Now it appears in `find.all Int` :+1:

### CODE REVIEW

**Comment by runarorama** [comment]
You'll also need a runtime representation of `mod`. Check `Rt1.hs`.

**Comment by mitchellwrosen** [comment]
@runarorama I'll have to check when I'm back on my laptop, but the impression I got was much of the functionality was already implemented, it just wasn't appearing in `find`. It works when used in watch expressions already, for example.

**Comment by runarorama** [comment]
You're totally right, it's already implemented in the runtime.

**Comment by runarorama** [comment]
@mitchellwrosen add yourself to https://github.com/unisonweb/unison/blob/master/CONTRIBUTORS.markdown when you get a chance.

**Pull request merged**
