### PR TITLE
Implement IO.systemTime

### PR DESCRIPTION
**Pull request by BenFradet**
I originally wanted to implement an rng but I saw that `systemTime` wasn't implemented yet so I figured I'd give that a go first since it seems easier.

However, I'm currently stuck with this error message:

```
typechecking failedfromList [TypeError (ErrorNote {cause = AbilityCheckFailure [] [#3Niar] Γ
  |start|
  'User "start"
  IO.rethrow15 : #5cbWz9X1yc #4CwT8MvGSh a ->{#3NiarmqmEP} a
  IO.openFile22 : #2raeQMvsAJ -> #2FhgNYaH6r ->{#3NiarmqmEP} #2raeQMvsAJ
  IO.closeFile26 : #2raeQMvsAJ ->{#3NiarmqmEP} ()
  IO.isFileEOF30 : #2raeQMvsAJ ->{#3NiarmqmEP} ##Boolean
  IO.isFileOpen34 : #2raeQMvsAJ ->{#3NiarmqmEP} ##Boolean
  IO.getLine38 : #2raeQMvsAJ ->{#3NiarmqmEP} ##Text
  IO.getText42 : #2raeQMvsAJ ->{#3NiarmqmEP} ##Text
  IO.putText49 : #2raeQMvsAJ -> ##Text ->{#3NiarmqmEP} ()
  |𝕩50|
  'Inference Other-50
  'User "a"-51, path = fromList [InSynthesizeApp ((#5cbWz #4CwT8 Var 'User "a"-51) -> (({[#3Niar]} Var 'User "a"-51))) #3Niar#26 1,InFunctionCall [User "a"-51] Var User "IO.rethrow"-15 ((#5cbWz #4CwT8 Var 'User "a"-51) -> (({[#3Niar]} Var 'User "a"-51))) [#3Niar#26],InSynthesize (Var User "IO.rethrow"-15 #3Niar#26),InCheck (Var User "IO.rethrow"-15 #3Niar#26) (({[#3Niar]} ##Nat)),InSynthesize (Var User "IO.rethrow"-15 #3Niar#26:({[#3Niar]} ##Nat)),InSynthesize (let Var User "IO.rethrow"-15 #3Niar#26:({[#3Niar]} ##Nat) in (IO.systemTime. (let Handle "stderr":#2raeQ in (IO.stderr. (let Handle "stdout":#2raeQ in (IO.stdout. (let (λ (t. Cycle (_1. (let rec[Var User "IO.putText"-49 Var User "IO.stdout" Var User "t"] in Var User "IO.putText"-49 Var User "IO.stdout" "\n")))):##Text -> ({[#3Niar]} #51bxy) in (IO.printLine. (let Handle "stdin":#2raeQ in (IO.stdin. (let (λ ((). Var User "IO.getLine"-38 Var User "IO.stdin")):#51bxy -> ({[#3Niar]} ##Text) in (IO.readLine. #51bxy#0)))))))))))),InSynthesize (let (λ (h. (λ (t. Var User "IO.rethrow"-15 (#3Niar#16 Var User "h" Var User "t"))))):#2raeQ -> ##Text -> ({[#3Niar]} #51bxy) in (IO.putText. (let Var User "IO.rethrow"-15 #3Niar#26:({[#3Niar]} ##Nat) in (IO.systemTime. (let Handle "stderr":#2raeQ in (IO.stderr. (let Handle "stdout":#2raeQ in (IO.stdout. (let (λ (t. Cycle (_1. (let rec[Var User "IO.putText" Var User "IO.stdout" Var User "t"] in Var User "IO.putText" Var User "IO.stdout" "\n")))):##Text -> ({[#3Niar]} #51bxy) in (IO.printLine. (let Handle "stdin":#2raeQ in (IO.stdin. (let (λ ((). Var User "IO.getLine"-38 Var User "IO.stdin")):#51bxy -> ({[#3Niar]} ##Text) in (IO.readLine. #51bxy#0)))))))))))))),InSynthesize (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#1 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text) in (IO.getText. (let (λ (h. (λ (t. Var User "IO.rethrow"-15 (#3Niar#16 Var User "h" Var User "t"))))):#2raeQ -> ##Text -> ({[#3Niar]} #51bxy) in (IO.putText. (let Var User "IO.rethrow"-15 #3Niar#26:({[#3Niar]} ##Nat) in (IO.systemTime. (let Handle "stderr":#2raeQ in (IO.stderr. (let Handle "stdout":#2raeQ in (IO.stdout. (let (λ (t. Cycle (_1. (let rec[Var User "IO.putText" Var User "IO.stdout" Var User "t"] in Var User "IO.putText" Var User "IO.stdout" "\n")))):##Text -> ({[#3Niar]} #51bxy) in (IO.printLine. (let Handle "stdin":#2raeQ in (IO.stdin. (let (λ ((). Var User "IO.getLine"-38 Var User "IO.stdin")):#51bxy -> ({[#3Niar]} ##Text) in (IO.readLine. #51bxy#0)))))))))))))))),InSynthesize (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#0 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text) in (IO.getLine. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#1 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text) in (IO.getText. (let (λ (h. (λ (t. Var User "IO.rethrow"-15 (#3Niar#16 Var User "h" Var User "t"))))):#2raeQ -> ##Text -> ({[#3Niar]} #51bxy) in (IO.putText. (let Var User "IO.rethrow"-15 #3Niar#26:({[#3Niar]} ##Nat) in (IO.systemTime. (let Handle "stderr":#2raeQ in (IO.stderr. (let Handle "stdout":#2raeQ in (IO.stdout. (let (λ (t. Cycle (_1. (let rec[Var User "IO.putText" Var User "IO.stdout" Var User "t"] in Var User "IO.putText" Var User "IO.stdout" "\n")))):##Text -> ({[#3Niar]} #51bxy) in (IO.printLine. (let Handle "stdin":#2raeQ in (IO.stdin. (let (λ ((). Var User "IO.getLine" Var User "IO.stdin")):#51bxy -> ({[#3Niar]} ##Text) in (IO.readLine. #51bxy#0)))))))))))))))))),InSynthesize (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#18 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Boolean) in (IO.isFileOpen. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#0 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text) in (IO.getLine. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#1 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text) in (IO.getText. (let (λ (h. (λ (t. Var User "IO.rethrow"-15 (#3Niar#16 Var User "h" Var User "t"))))):#2raeQ -> ##Text -> ({[#3Niar]} #51bxy) in (IO.putText. (let Var User "IO.rethrow"-15 #3Niar#26:({[#3Niar]} ##Nat) in (IO.systemTime. (let Handle "stderr":#2raeQ in (IO.stderr. (let Handle "stdout":#2raeQ in (IO.stdout. (let (λ (t. Cycle (_1. (let rec[Var User "IO.putText" Var User "IO.stdout" Var User "t"] in Var User "IO.putText" Var User "IO.stdout" "\n")))):##Text -> ({[#3Niar]} #51bxy) in (IO.printLine. (let Handle "stdin":#2raeQ in (IO.stdin. (let (λ ((). Var User "IO.getLine" Var User "IO.stdin")):#51bxy -> ({[#3Niar]} ##Text) in (IO.readLine. #51bxy#0)))))))))))))))))))),InSynthesize (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#17 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Boolean) in (IO.isFileEOF. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#18 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Boolean) in (IO.isFileOpen. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#0 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text) in (IO.getLine. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#1 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text) in (IO.getText. (let (λ (h. (λ (t. Var User "IO.rethrow"-15 (#3Niar#16 Var User "h" Var User "t"))))):#2raeQ -> ##Text -> ({[#3Niar]} #51bxy) in (IO.putText. (let Var User "IO.rethrow"-15 #3Niar#26:({[#3Niar]} ##Nat) in (IO.systemTime. (let Handle "stderr":#2raeQ in (IO.stderr. (let Handle "stdout":#2raeQ in (IO.stdout. (let (λ (t. Cycle (_1. (let rec[Var User "IO.putText" Var User "IO.stdout" Var User "t"] in Var User "IO.putText" Var User "IO.stdout" "\n")))):##Text -> ({[#3Niar]} #51bxy) in (IO.printLine. (let Handle "stdin":#2raeQ in (IO.stdin. (let (λ ((). Var User "IO.getLine" Var User "IO.stdin")):#51bxy -> ({[#3Niar]} ##Text) in (IO.readLine. #51bxy#0)))))))))))))))))))))),InSynthesize (let (λ (f. Var User "IO.rethrow"-15 (#3Niar#2 Var User "f"))):#2raeQ -> ({[#3Niar]} #51bxy) in (IO.closeFile. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#17 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Boolean) in (IO.isFileEOF. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#18 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Boolean) in (IO.isFileOpen. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#0 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text) in (IO.getLine. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#1 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text) in (IO.getText. (let (λ (h. (λ (t. Var User "IO.rethrow"-15 (#3Niar#16 Var User "h" Var User "t"))))):#2raeQ -> ##Text -> ({[#3Niar]} #51bxy) in (IO.putText. (let Var User "IO.rethrow"-15 #3Niar#26:({[#3Niar]} ##Nat) in (IO.systemTime. (let Handle "stderr":#2raeQ in (IO.stderr. (let Handle "stdout":#2raeQ in (IO.stdout. (let (λ (t. Cycle (_1. (let rec[Var User "IO.putText" Var User "IO.stdout" Var User "t"] in Var User "IO.putText" Var User "IO.stdout" "\n")))):##Text -> ({[#3Niar]} #51bxy) in (IO.printLine. (let Handle "stdin":#2raeQ in (IO.stdin. (let (λ ((). Var User "IO.getLine" Var User "IO.stdin")):#51bxy -> ({[#3Niar]} ##Text) in (IO.readLine. #51bxy#0)))))))))))))))))))))))),InSynthesize (let (λ (f. (λ (m. Var User "IO.rethrow"-15 (#3Niar#25 Var User "f" Var User "m"))))):#2raeQ -> #2FhgN -> ({[#3Niar]} #2raeQ) in (IO.openFile. (let (λ (f. Var User "IO.rethrow"-15 (#3Niar#2 Var User "f"))):#2raeQ -> ({[#3Niar]} #51bxy) in (IO.closeFile. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#17 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Boolean) in (IO.isFileEOF. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#18 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Boolean) in (IO.isFileOpen. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#0 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text) in (IO.getLine. (let (λ (h. Var User "IO.rethrow"-15 (#3Niar#1 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text) in (IO.getText. (let (λ (h. (λ (t. Var User "IO.rethrow"-15 (#3Niar#16 Var User "h" Var User "t"))))):#2raeQ -> ##Text -> ({[#3Niar]} #51bxy) in (IO.putText. (let Var User "IO.rethrow"-15 #3Niar#26:({[#3Niar]} ##Nat) in (IO.systemTime. (let Handle "stderr":#2raeQ in (IO.stderr. (let Handle "stdout":#2raeQ in (IO.stdout. (let (λ (t. Cycle (_1. (let rec[Var User "IO.putText" Var User "IO.stdout" Var User "t"] in Var User "IO.putText" Var User "IO.stdout" "\n")))):##Text -> ({[#3Niar]} #51bxy) in (IO.printLine. (let Handle "stdin":#2raeQ in (IO.stdin. (let (λ ((). Var User "IO.getLine" Var User "IO.stdin")):#51bxy -> ({[#3Niar]} ##Text) in (IO.readLine. #51bxy#0)))))))))))))))))))))))))),InSynthesize Cycle (IO.systemTime. (IO.putText. (IO.getText. (IO.getLine. (IO.isFileOpen. (IO.isFileEOF. (IO.closeFile. (IO.openFile. (IO.readLine. (IO.printLine. (IO.rethrow. (IO.stderr. (IO.stdout. (IO.stdin. (let rec[Var User "IO.rethrow" #3Niar#26:({[#3Niar]} ##Nat),(λ (h. (λ (t. Var User "IO.rethrow" (#3Niar#16 Var User "h" Var User "t"))))):#2raeQ -> ##Text -> ({[#3Niar]} #51bxy),(λ (h. Var User "IO.rethrow" (#3Niar#1 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text),(λ (h. Var User "IO.rethrow" (#3Niar#0 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Text),(λ (h. Var User "IO.rethrow" (#3Niar#18 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Boolean),(λ (h. Var User "IO.rethrow" (#3Niar#17 Var User "h"))):#2raeQ -> ({[#3Niar]} ##Boolean),(λ (f. Var User "IO.rethrow" (#3Niar#2 Var User "f"))):#2raeQ -> ({[#3Niar]} #51bxy),(λ (f. (λ (m. Var User "IO.rethrow" (#3Niar#25 Var User "f" Var User "m"))))):#2raeQ -> #2FhgN -> ({[#3Niar]} #2raeQ),(λ ((). Var User "IO.getLine" Var User "IO.stdin")):#51bxy -> ({[#3Niar]} ##Text),(λ (t. Cycle (_1. (let rec[Var User "IO.putText" Var User "IO.stdout" Var User "t"] in Var User "IO.putText" Var User "IO.stdout" "\n")))):##Text -> ({[#3Niar]} #51bxy),(λ (x. (case Var User "x" of [MatchCase Constructor #5cbWz 0 [Var] Nothing (e. (#3Niar#15 Var User "e")),MatchCase Constructor #5cbWz 1 [Var] Nothing (a. Var User "a")]))):(a. #5cbWz #4CwT8 Var User "a" -> ({[#3Niar]} Var User "a")),Handle "stderr":#2raeQ,Handle "stdout":#2raeQ,Handle "stdin":#2raeQ] in #51bxy#0)))))))))))))))]})]
CallStack (from HasCallStack):
  error, called at src/Unison/Runtime/IOSource.hs:33:38 in unison-parser-typechecker-0.1-KdnhuHkmR1l6kLgRtBDHi5:Unison.Runtime.IOSource
```

Note: I still need to use `EpochTime` but I didn't bother as a first pass

### CODE REVIEW

**Comment by pchiusano** [comment]
@BenFradet sorry for the trouble you're having!

For now, when working on `IOSource`, I'd start by copying it to a regular file, `IO.u`, and then starting up the command line tool and saving that `IO.u` file to trigger typechecking of it. Then you'll get nicely formatted error messages with line numbers that you don't have to translate back to the original source. Once you get it compiling, you can then paste it back into the `IOSource.hs` file.

If you are having trouble with figuring out the error after doing that, feel free to post it here or ping in Gitter.

**Comment by BenFradet** [comment]
Ah thanks for sharing the methodology!

**Comment by BenFradet** [comment]
Thanks, I was able to make it work with your explanation.

However, how do I go about writing tests for a feature like this one?

**Comment by pchiusano** [comment]
Sorry for delay. 

Re: testing, I'm thinking let's just have the tests in pure Unison, run via the `execute` command. A couple things I think you'll need to make this possible:

* Add some way of launching `unison` in batch mode - basically, run one command, then exit. Suggested syntax `unison mybranch/execute IO.tests`. Other possibility: just pipe a file to the `unison` executable, seems like that should just work.
* Will need some way of exiting the process, like `IO.exit : Nat ->{IO} a`.
* Some convenience functions for constucting `IO`-based tests. In [#477](https://github.com/unisonweb/unison/pull/477#issuecomment-489649161) I mentioned a `Test` ability, and I think you could use that same ability for `IO` tests, those will just be of type `{IO, Test} a` rather than just `{Test} a`. That `ability Test` hasn't been written yet, though. (If you'd like, try porting [EasyTest](https://github.com/unisonweb/unison/tree/master/yaks/easytest) to Unison and let us know how that goes)
* Then you can tell Travis to run these Unison-based tests, and it will pick up the exit code.

Also possibly related - #417 which will make it easier to iterate on the tests during development.

**Comment by pchiusano** [comment]
👍  

okay merging, thanks @BenFradet!

**Comment by BenFradet** [comment]
Thanks a lot, I'll have a go

**Pull request merged**
