### PR TITLE
Fix jit `zlib-deflate`

### PR DESCRIPTION
**Pull request by dolio**
The procedure uses concurrency and streaming to handle the checksum, but it wasn't actually reading concurrently from the pipe with a limited buffer capacity, causing deadlocks for large enough byte strings.

### CODE REVIEW

**Comment by dolio** [comment]
FYI, I tried inflating the big value, and it worked. But maybe I should try inflating an _input_ that is bigger than 4096 bytes?

**Comment by pchiusano** [comment]
Maybe add a check for `gzip` while you're at it, not sure if it uses the same approach.

**Comment by dolio** [comment]
Inflating a big compressed input seems to work fine.

**Comment by dolio** [comment]
The racket gzip implementation seems to have a completely different, non-streaming API, so it just works.

Actually, I guess it is stream based, but it doesn't need us to add our own checksumming to the stream like zlib does.

**Review by aryairani — APPROVED** [review]

**Pull request merged**
