### PR TITLE
Fix #785: Allow sequence literals as arguments to constructors

### LINKED ISSUE #785: Can't parse [ ] pattern inside of constructor pattern
```
type X a = X [a]

bad : X a -> a
bad x = case x of
  X.X [b] -> b

good : X a -> a
good x = case x of
  X.X ([b]) -> b
```
```
  /Users/arya/unison/u.u:5:7:
  unexpected [
      5 |   X.X [b] -> b
                ^
```

### PR DESCRIPTION
**Pull request by noahhaasis**
This fixes #785 by allowing sequence literals, which are handled separately from all other values, as arguments to constructors.

### CODE REVIEW

**Comment by francisdb** [comment]
no test case?

**Comment by noahhaasis** [comment]
@francisdb Sry completely forgot them.

**Comment by pchiusano** [comment]
Looks great, thanks! Will merge after Travis is done.

**Comment by francisdb** [comment]
@noahhaasis no sorry needed, you're doing a way better job at contributing than me

**Comment by aryairani** [comment]
@francisdb @noahhaasis We definitely appreciate both of y’all.

**Pull request merged**
