### PR TITLE
update the name of the pre-release build

### PR DESCRIPTION
**Pull request by aryairani**
per https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1702495233966029 which will be accessible until mid-March

### CODE REVIEW

**Review by ceedubs — APPROVED** [review]
Looks good to me. Is there anywhere else that we'd need to update documentation?

**Comment by aryairani** [comment]
> Looks good to me. Is there anywhere else that we'd need to update documentation?
Good question — @rlmark Do you know?

This PR is about changing the nomenclature and url for UCM binaries that are built off of `trunk` 
from "latest" / `https://github.com/unisonweb/unison/archive/refs/tags/latest.zip` / `https://github.com/unisonweb/unison/releases/download/latest/ucm-windows.zip` / etc.

to "trunk" / `https://github.com/unisonweb/unison/archive/refs/tags/trunk.zip` / `https://github.com/unisonweb/unison/releases/download/trunk/ucm-windows.zip` / etc.

**Comment by aryairani** [comment]
this may require a corresponding change to the homebrew formula for —head. is there one for nix too?

**Comment by ceedubs** [comment]
> this may require a corresponding change to the homebrew formula for —head. is there one for nix too?

No, not with the way that the derivation is currently set up.

**Comment by rlmark** [comment]
You should be good! We don't link to the pre-release builds for the installs page, only the official latest ones!

**Review by rlmark — APPROVED** [review]

**Pull request merged**
