### PR TITLE
Remove Sync22

### PR DESCRIPTION
**Pull request by ChrisPenner**
## Overview

Following #5013 Sync22 is no longer used, and also doesn't have any significant testing in place.

I can see arguments for either keeping it or removing it;
In theory it's nice to have some sort of way to sync code between local codebases, even though we don't have any user workflows for doing that right now,

On the other hand, it represents a pretty big chunk of low-level sqlite code that I've often found myself needing tweak or update to keep up-to-date, and I don't believe it's tested well at the moment, esp. once git is removed.

## Implementation notes

* Removes Sync22 functionality

## Test coverage

* This chunk of code isn't used and doesn't seem to be tested.

### CODE REVIEW

**Comment by aryairani** [comment]
> and also doesn't have any significant testing in place.

Is this just a matter of coming up with some tests? I could imagine: syncing a project branch from one codebase to another; and then some kind of consistency check i guess

> it represents a pretty big chunk of low-level sqlite code that I've often found myself needing tweak or update to keep up-to-date

would you say more about these tweaks and updates?

**Comment by ceedubs** [comment]
I have no idea what Sync22 is, but #3837 came up as something that could potentially benefit from this code.

**Comment by ChrisPenner** [comment]
> would you say more about these tweaks and updates?

Mostly it was just when I was splitting up the serializers/deserializers so I could easier use them in Share I had to patch a few conversion functions and stuff in Sync22; maybe now that that's done it'll come up less often 😄 .

I tend to lose trust in codepaths that aren't being exercised often, E.g. MigrateSchema1to2 we KNOW is pretty broken at this point because it's not tested and has been sitting around to bitrot for too long.

**Review by aryairani — APPROVED** [review]

**Comment by ChrisPenner** [comment]
Arya and I decided if we do want to support codebase-to-codebase direct sync we should do it using SyncV2 instead; that way we only have a single implementation for both Share and UCM; plus that way you can "sync" to a file to send to your buddy without needing to share your whole codebase.

**Pull request merged**
