### PR TITLE
Add Ed25519 to racket crypto.rkt

### PR DESCRIPTION
**Pull request by jaredly**
re: https://github.com/unisonweb/unison/issues/4709

There's some plumbing left to fully hook it into the jit, but this has the core implementation completed.

To test: `raco test scheme-libs/racket/unison/crypto.rkt`

I got the values for the tests from the following scratch:

```

zseed =   0xs0000000000000000000000000000000000000000000000000000000000000000
-- used https://slowli.github.io/ed25519-quirks/basics/ to determine the public key value
zpublic = 0xs3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29

> crypto.Ed25519.sign.impl zseed zpublic 0xs
-- Produces: Right 0xs8f895b3cafe2c9506039d0e2a66382568004674fe8d237785092e40d6aaf483e4fc60168705f31f101596138ce21aa357c0d32a064f423dc3ee4aa3abf53f803

-- the concatenation of "signature point" and "signature scalar"
zsig = 0xs8f895b3cafe2c9506039d0e2a66382568004674fe8d237785092e40d6aaf483e4fc60168705f31f101596138ce21aa357c0d32a064f423dc3ee4aa3abf53f803

> crypto.Ed25519.verify.impl zpublic 0xs zsig
-- Produces "Right True"

```

### CODE REVIEW

**Comment by aryairani** [comment]
@jaredly Should I go ahead and merge this for any reason, or should I wait for the rest of the integration work?

@pchiusano @SystemFw not sure if you want to review this, or if it's just due to past collab that Jared added you, but would you leave a note indicating either any feedback or just that you're waiving review

**Comment by SystemFw** [comment]
I'm not sure I can add much, Jared is the most knowledgeable about ffi

**Review by SystemFw — COMMENTED** [review]
Roughly LGTM, but I'm not sure I know enough to provide meaningful feedback in any case

**Comment by jaredly** [comment]
Feel free to merge, I'll do the integration in a separate pr

**Review by aryairani — APPROVED** [review]
🤷‍♂️

**Pull request merged**
