### PR TITLE
feat: add `edit.dependents`

### PR DESCRIPTION
**Pull request by mitchellwrosen**
## Overview

This PR adds a small variant of `edit` that also grabs all of the thing's transitive dependents. This is intended as sort of a temporary solution to the known issue of ending up in the following situation:

- `foo` depends on `bar` depends on `Baz`
- `foo` and `Baz` are in the scratch file
- `Baz` is changed in the file but not saved to the codebase yet
- type errors coming from `foo` are missing names, because it's calling `bar` which is still calling old-now-nameless `Baz`

The fix in this small example is to `edit bar`, but more generally an `edit.dependents Baz` here will do what you want – get the full transitive closure of dependents in the file (so that any changes to `Baz` are fully propagated within the file).

## Interesting/controversial decisions

Not very controversial, but I also made it so temporary output messages that are displayed only within a console region are now also visible in transcripts. Ever `merge` in a transcript is now a lot more verbose but I think that's totally fine because transcripts are meant to capture ucm output.

## Test coverage

I've added a new transcript. I tried just adding onto the end of `edit-command.md`, but was getting really strange results. You can already see in that transcript one instance of spookiness that was worked around just by repeating a stanza. Our transcript runner has some terrible bug.

### CODE REVIEW

**Comment by aryairani** [comment]
A little bit of a change in how we set up transcripts now; I sent @sellout a request to clarify on #5406, or you can follow up out-of-band

**Review by aryairani — COMMENTED** [review]
Thanks, this will be good.
We should set up a time soon to sort out the longer-term fix.

**Review by aryairani — APPROVED** [review]

**Comment by sellout** [comment]
> A little bit of a change in how we set up transcripts now; I sent @sellout a request to clarify on #5406, or you can follow up out-of-band

For this PR, I think you should
1. move edit-dependents-command.md into transcripts/idempotent/;
2. revert the other changes in transcripts/; and
3. run `stack exec transcripts` to update the results in the new transcript layout.

Alternatively, you could
1. delete transcripts/edit-dependents-command.md;
2. move (note: “.output” gets removed in the moves)
   - transcripts/edit-dependents-command.output.md → transcripts/idempotent/edit-dependents-command.md,
   - transcripts/fix-5326.output.md → transcripts/idempotent/fix-5326.md, and
   - transcripts/help.output.md → transcripts/idempotent/help.md;
3. stage everything; and
4. run `stack exec transcripts` and ensure that the diff has only cosmetic changes.

The result should be the same either way. the latter maybe gives a bit more confidence that the new transcript results match the ones you got before merging in trunk.

**Comment by aryairani** [comment]
bump @mitchellwrosen re merge conflicts

**Comment by mitchellwrosen** [comment]
@aryairani Oops, done now!

**Pull request merged**
