### PR TITLE
Add Author and License metadata types to builtins

### PR DESCRIPTION
**Pull request by pchiusano**
See discussion [here](https://github.com/unisonweb/unison/issues/1128#issuecomment-584732483). 

Notes:

* Year is `Year Nat`, common era year. If someone discovers ancient Babylonian tablets containing Unison code, we may need to revisit.
* This deletes `builtins` from the initial codebase namespace - it starts out empty, see #1056 and there's a transcript, see `emptyCodebase.md` in the transcripts directory.
* As a result of deleting `builtins`, I had to add a `ucm` block at the start of most transcripts to do a `builtins.merge` to avoid transcript failures or changes to their output. Some of the transcript output is changed just due to there being an extra entry in the history (history starts out empty, then the `builtins.merge` adds a bunch of names into the namespace).

Next up, we will try using the PR process to add these to base!!!

### CODE REVIEW

**Comment by pchiusano** [comment]
@runarorama - you can run a transcript via ucm transcript.fork to start the transcript from some existing codebase. Like the transcripts used to generate some of the docs on the website start from a codebase that just has base.

But if you are making a totally self contained transcript that starts from an empty codebase, then the transcript will generally begin by fetching its dependencies - pulling base or doing builtins.merge.

**Comment by aryairani** [comment]
I guess we could have a command-line flag that says whether `builtin.` gets added or not?

**Comment by pchiusano** [comment]
Yeah, maybe ucm transcript.builtins or something that runs a transcript starting from just the builtins. I think that’s my vote - the transcript runner should by default start from the same state as a blank codebase.

Or maybe ucm transcript behaves as before (Can access builtins) and we add ucm transcript.fork0 or something to start a transcript without access to even builtins?

**Comment by runarorama** [comment]
I think we can address these concerns in a separate PR. My vote is to either put the builtins behind a flag, or put the blank codebase behind a flag. Either way is fine with me.

**Comment by aryairani** [comment]
Sounds good; I vote we put the builtins behind a flag.

Side note @pchiusano if we had `unique` terms, maybe we could avoid needing a visible GUID in the `Author` object.  (Is there a different ticket this comment should go into?)

**Pull request merged**
