### PR TITLE
FQN elision - pretty-printer now emits `use` statements

### LINKED ISSUE #285: Pretty-printing should emit `use` statements rather than needing FQNs everywhere
Just tracking this as an actual issue. A proposed algorithm described here:

https://github.com/unisonweb/unison/pull/269#issuecomment-444998664

@atacratic if you are working on this you can assign it to yourself :)

### PR DESCRIPTION
**Pull request by atacratic**
Fixes #285 

There's a long comment in TermPrinter.hs explaining the spec and design, but it matches the plan discussed in #285.

I expect people won't love the `Prefix`/`Suffix` stuff in PrettyPrintEnv.hs (and related definitions `splitName`/`joinName` in TermPrinter.hs) since I see some `NameSegment` stuff in branchless that looks similar/better.  I'll be honest: I'm hoping someone else will sort this out as part of the branchless merge when it comes.

### CODE REVIEW

**Comment by pchiusano** [comment]
Nice!! Looking forward to reviewing!

Could you move the merge target to wip/branchless? It will shortly become master. Changes should be minimal to none.

**Comment by pchiusano** [comment]
Actually, disregard, will merge to master and we will sort it out.

**Comment by pchiusano** [comment]
Very cool, thanks for all your work on this. 😎👍 I did a quick review and appreciate all the docs you wrote, it makes it very clear how it is supposed to work which makes digging into the code easy.

Was there anything in particular in the code that you wanted more of a review of?

**Comment by atacratic** [comment]
Thanks @pchiusano for handling the merging!

On stuff to review:
- Have I got cases for the right things when counting occurrences of names ([suffixCounterTerm](https://github.com/unisonweb/unison/pull/515/files#diff-b603d4c6ba5cb488a51cf97d057e8f1eR627))?  In particular I was a bit perplexed about whether `Var` is just for locals where qualification isn't necessary/used.
- the Suffix/Prefix type aliases [here](https://github.com/unisonweb/unison/pull/515/files#diff-195096a684c199c7d88beaeb1584332dR84) (c.f. [Codebase.NameSegment](https://github.com/unisonweb/unison/blob/wip/branchless/parser-typechecker/src/Unison/Codebase/NameSegment.hs))

Other stuff that might be worth a skim:
- the tests, starting [here](https://github.com/unisonweb/unison/blob/wip/branchless/parser-typechecker/tests/Unison/Test/TermPrinter.hs#L357): is it producing the sort of output you were hoping for?
- [fromNameHash](https://github.com/unisonweb/unison/pull/515/files#diff-72129240b002370c4e3c76ac5ae481f0R54)
- the helpers [ABT.extraMap](https://github.com/unisonweb/unison/pull/515/files#diff-05410ab7c41bea7bc4478c3c4875f364R168), [ABT.find](https://github.com/unisonweb/unison/pull/515/files#diff-05410ab7c41bea7bc4478c3c4875f364R511), [Pattern.foldMap'](https://github.com/unisonweb/unison/pull/515/files#diff-7019966e073d2d365911be747f3b555aR135), [Term.extraMap](https://github.com/unisonweb/unison/pull/515/files#diff-fec9994c79b3350a1bbb57c6ff494361R177)

**Pull request merged**
