### PR TITLE
put builtin term types into codebase (fixes #776)

### LINKED ISSUE #776: Write builtin terms' type to `v1/terms/_builtin/<escaped-name>/type.ub` on ucm startup.
Do we want to do this? Why or why not? /cc @mitchellwrosen 

Pros:
* type info for builtins is visible to external tools

Cons:

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This patch adds builtin terms' types to the codebase during initialization

### CODE REVIEW

**Comment by aryairani** [comment]
Looks good.  I'll note that this only happens during codebase initialization and not at ucm startup, and while that's already an improvement, but it won't necessarily populate for new builtins as we add them.

Maybe we just need to reinitialize the codebase on startup?  Or write missing builtins on startup?

**Comment by mitchellwrosen** [comment]
@aryairani Yah, only happens on the very first init. I'm not totally sure how adding new builtins is meant to work. Want to hash that out before merging, or tackle it in a different ticket/PR?

**Comment by aryairani** [comment]
@mitchellwrosen I'm leaning slightly towards hashing it out before merging, but it wouldn't take much to convince me otherwise.

**Comment by aryairani** [comment]
Per private slack conversation, we're gonna put this on the back burner until we have more clarity.

**Comment by aryairani** [comment]
Gonna close this for now (also it no longer merges cleanly 😞), but we can always revisit.

**Pull request closed without merging**
