### PR TITLE
bugfix: fix suffixification logic in upgrade

### PR DESCRIPTION
**Pull request by mitchellwrosen**
## Overview

Same as #5311, but for `upgrade`.

## Test coverage

Transcript included

### CODE REVIEW

**Review by aryairani — APPROVED** [review]
Nice, thanks.

Could you add a few words to the transcript about what is being demonstrated? Was it `b.y` being rendered wrong in `c`?

**Comment by mitchellwrosen** [comment]
@aryairani Yep, see the first commit for the busted transcript.

**Comment by aryairani** [comment]
> @aryairani Yep, see the first commit for the busted transcript.

I did see that—thanks for including it—but still generally want the final checked-in transcripts to be self-documenting. I know we have other tech debt in that area so I'm only singling this one out because we're in the process of adding it.

**Comment by mitchellwrosen** [comment]
@aryairani Yep, I'm on it

**Pull request merged**
