### PR TITLE
Reject `.` in symbol names, allow symbols in FQNs at parse time

### LINKED ISSUE #2970: support symboly namesegments in scratch file parser
Verify whether this sort of thing can round trip; and propose a solution if not.
image

### PR DESCRIPTION
**Pull request by ChrisPenner**
This is a revival of #2975 which went stale;

We wanted to wait a while so that base versions with `.` in them went stale, I think we've waited long enough to move forwards. ~Folks can always rename or delete terms in their codebases if they hit an edge case 😄~ we've discovered that because this changes the parser, users will be unable to interact with terms in their codebase containing `.`s. This is potentially an issue; for now they can use the `M4`  release to rename them to avoid problems. If users continue to encounter this issue in the future we can certainly add some `debug.fix-name` command.

fixes #2970 

## Overview

* Support parsing things like: `Nat.-.doc = {{ my doc}}`
* As a result this supports nested symbols in paths and such, not that I expect folks will use that often: `(Nat.-.+) a b = a + b`
* **Disallows `.` in operator names**, this means any codebases with existing operators that use `.` in their names will fail to round-trip and will need to be re-named.
  * Is anyone aware of common operators here? AFAIK `base` has switched from `.` to `>>`. cc @runarorama 

## Implementation notes

* Alters the `id` parser to support any type of id as each segment of a path, selecting the identifier type based only on the terminal segment.
* Since `.` is no longer a valid symbol, I added a new token to the lexer which is used for the dot in `forall x. x` since that was previously a `SymbolyId`.

## Interesting/controversial decisions

Disallowing `.` in operator names might be controversial, but I think having overlap between our hierarchy designator and operator names is likely to cause confusion in the long run, so maybe best to rip that bandaid off before it's too late to do so.

We will need to consider the impact this has on users who use `.` in operator names already, since any of those terms will fail to round-trip now 🤔 . We might be able to get away with it since we've already added new names for `.` in base; but if they've forked base they might still have `.` in their codebase.

We could consider supporting existing escaped versions, e.g. `\.`, but how long would we support that? Would it be stuck around forever?

## Test coverage

Added a regression transcript.

- - -
This change is [Reviewable](https://reviewable.io/reviews/unisonweb/unison/2975)

### CODE REVIEW

**Comment by aryairani** [comment]
> We could consider supporting existing escaped versions, e.g. \., but how long would we support that? Would it be stuck around forever?

Instead of `\`-style escaping, I'm imagining escaping individual name segments with a markdown codespan style `` `.` ``. 

Segments with backticks would be escaped with bigger groups of backticks. ``` `` ` `` ``` etc. Leading and trailing spaces would be ignored. This could stick around forever.

**Comment by aryairani** [comment]
> for now they can use the `M4` release to rename them to avoid problems

We noticed this is not true either due to the migration in M4a;
I think we need at least a `debug.fix-name` (if not support for escaping name segments) or risk stranding some unusable identifiers in the namespace.

Another proposal was to automatically migrate names and ignore history, but feels hacky.

Could we do a level-of-effort estimate for escaping name segments?

**Comment by aryairani** [comment]
Latest proposal to get this mergeable was to implement markdown-style name segment escaping but for the time being only make it available to ucm commands.

This wouldn't just help with names with `.` but any of the wordy or symboly keywords, a set which can grow or shrink over time.

**Review by aryairani — CHANGES_REQUESTED** [review]
Latest proposal to get this mergeable was to implement markdown-style name segment escaping but for the time being only make it available to ucm commands.

This wouldn't just help with names with `.` but any of the wordy or symboly keywords, a set which can grow or shrink over time.

**Comment by runarorama** [comment]
I note that this is missing a couple of changes. There are (legacy?) lexers at the bottom of Lexer.hs that are called from the Path parser and the Term printer. I don’t see updates to those here, and they should probably be updated or removed. They duplicate the wordy/symboly lexing logic.

**Comment by runarorama** [comment]
Related issue: https://github.com/unisonweb/unison/issues/3362. Properly implemented, this PR should address that issue.

**Comment by ChrisPenner** [comment]
Yeah, this PR has already been refreshed once, and looks to have gone stale again while we wait.

I'm going to wait until all the blockers are cleared then refresh it one last time haha. Thanks for the tip

**Comment by aryairani** [comment]
@runarorama This PR is superseded by https://github.com/unisonweb/unison/pull/3525
@ChrisPenner you are off the hook for refreshing 😀

**Pull request closed without merging**
