### PR TITLE
Float Library Functions

### PR DESCRIPTION
**Pull request by billy1kaplan**
Adds float functions as described in #427

### CODE REVIEW

**Comment by francisdb** [comment]
Any chance you could add a fromText: Text->Either[String, Float]?

**Comment by billy1kaplan** [comment]
As far as I can tell, using the Unison either type in these functions might be a bit more challenging.

Either is defined here:
https://github.com/unisonweb/unison/blob/ed69a95128440f7976014d2826a0e0872662ba43/parser-typechecker/src/Unison/Runtime/IOSource.hs#L119


We could pretty easily add `fromText: Text -> Optional Float` if that's an acceptable alternative.

**Comment by pchiusano** [comment]
@billy1kaplan this is great, thanks, can you add yourself to CONTRIBUTORS? :)

Also, `Float.fromText : Text -> Optional Float` sounds good to me.

**Comment by francisdb** [comment]
Optional should indeed be enough. The user can easily come up with a proper error message for this simple case.

**Comment by pchiusano** [comment]
Thanks @billy1kaplan 🎸😀 merging...

**Pull request merged**
