### PR TITLE
Ensure we don't hang on 'open'

### PR DESCRIPTION
**Pull request by ChrisPenner**
## Overview

Cody ran into a situation where `xdg-open` would just hang if there wasn't a valid Display environment.

Easiest solution is to just 'fire-and-forget' the open command, and just cancel the thread if the auth callback finishes regardless of how that happens (e.g. if the user ends up copy-pasting to the browser manually that's fine, just shut down the open command which might be hung).

## Implementation notes

* Print the message with the URL before trying the open command
* Use `withAsync` to fork the open command, it will kill the open command if the MVar is fulfilled for any reason.

## Test coverage

Tried it out and it works for me, but I'll get @ceedubs  to try it too :)

### CODE REVIEW

**Review by ceedubs — APPROVED** [review]
@ChrisPenner worked splendidly for me. Thanks!

**Comment by tstat** [comment]
One thing I don't like about this solution is that we still call xdg-open regardless.

I think we could benefit from a clear distinction between running ucm headless or not. Perhaps a command line flag that determines if we are running in headless mode or not, then this and other/future similar issues can just switch on that.

**Comment by ChrisPenner** [comment]
@tstat I agree, and have a tracking issue here:  https://github.com/unisonweb/unison/issues/3082

That does seem like a different issue though and I don't think it should hold up this PR; especially since in this case Cody is actually still running an interactive session 😄

**Comment by tstat** [comment]
Oh, I didn't mean headless as in stdout is not a tty, I meant: "I am not in a desktop environment or I don't want ucm to interact with me in ways beyond the terminal".

**Comment by ChrisPenner** [comment]
FYI we actually have a `headless` command for UCM which doesn't even connect the TTY, so I assumed that's what you were referring to 😄

**Pull request merged**
