### PR TITLE
Add FindPatchI outputs to LoopState's numberedArgs

### PR DESCRIPTION
**Pull request by pt2121**
### WIP

re #838

🤞

### CODE REVIEW

**Comment by aryairani** [comment]
Hi @pt2121, this looks good!  Three questions:
1) Your comment above says “WIP”, is there more you want to do before merging?
2) Have you already added yourself to Contributors.md?
3) Would you be up to adding a transcript test for this functionality (see #816).  maybe the test could create a patch, and then find it using your WIP, then view the patch referenced by number?

**Comment by pchiusano** [comment]
+1 on adding a transcript test for this. See unison-src/transcripts for some examples and do stack exec transcripts to run all the transcripts in that directory. Travis will also run all the transcript tests.

**Comment by pt2121** [comment]
Hi guys,

Thanks for the cool project and your reviews.
I added WIP because I see the `find.patch` result is not numbered and wanted to double check that it's an expect behavior.
I'll add myself in to `Contributors.md` and look into adding the test.

**Comment by aryairani** [comment]
Oops, yes, thanks for pointing that out. The numbers will be important too.  

You can find some somewhat ugly examples of the number rendering at https://github.com/unisonweb/unison/blob/e08581b63bbd5d324993f4c3717ddb1d9f6598ef/parser-typechecker/src/Unison/CommandLine/OutputMessages.hs#L295-L302 and https://github.com/unisonweb/unison/blob/e08581b63bbd5d324993f4c3717ddb1d9f6598ef/parser-typechecker/src/Unison/CommandLine/OutputMessages.hs#L1021-L1022, and then update the `ListOfPatches` case in that same file.  You don't have to use those same methods, but I'm guessing the `P.numbered` function will be helpful.

Thanks for the help!

**Comment by pt2121** [comment]
Updated, patches in the output are numbered now. However, I have an issue create a transcript test.

How can I simulate editing a unison file in the test?

```
.> edit hello
```

Here is an example of what I tried:

[ls-patch.md](https://gist.github.com/pt2121/e01b2b5c580c6ff2688c70ae4e9ef90c)

[ls-patch.output.md](https://gist.github.com/pt2121/c3704ac0800f30ae803034dd71b0a095)

Thanks

**Comment by pchiusano** [comment]
After doing the initial add, just have a second Unison code block with the updated definition. Then do an update as before.

The edit command dumps a definition to a scratch file but since the transcript isn’t working with literal scratch files (only the virtual scratch files you provide via code blocks), I don’t think that will be useful for transcripts. 😀

**Comment by pt2121** [comment]
Thanks for the pointer - I'm totally new to the tools. 

This is getting long so I started a thread in slack.

**Comment by aryairani** [comment]
@pt2121 Hey just wanted to check in to see if there was anything I could do to help with this? 😀

**Comment by pt2121** [comment]
@aryairani, I struggled to write the transcript test for this.

The number command seems to work fine when I tested on a shell:
Screen Shot 2019-10-04 at 11 01 26 AM

Unfortunately, I can't manage to get it to work with the test
Screen Shot 2019-10-04 at 11 17 29 AM

Any thoughts? Thanks!

**Comment by aryairani** [comment]
Doh, I see.

We just encountered [that same issue](#857) yesterday while working on another feature.  The temporary workaround has been "don't use numberedArgs in transcripts", which obviously is not a good workaround in this case!

I would recommend saying `view.patch p1` for now to verify that the rest of the transcript works, then go ahead and switch it back to `view.patch 1` before checking it in.  The PR will continue to fail the continuous integration test, but once we fix #857 we can re-run the build and go from there.

How does that sound?  Thanks!

**Comment by pt2121** [comment]
Sounds great. will update

**Comment by aryairani** [comment]
On second thought, wait — I think I have a fix (#860) for (#857); so let me get that merged, and then you merge `master` hopefully without too much pain 🤞, and then I think it should fix the error you're seeing?

**Comment by aryairani** [comment]
Ok, should be good to go; let me know?

**Comment by pt2121** [comment]
Yeah, the fix works great. I updated find-patch transcript and its output. Thanks again for your helps!

**Comment by pchiusano** [comment]
Very nice, thanks @pt2121 😀 merging now

**Comment by pt2121** [comment]
Thank you both!

**Pull request merged**
