### PR TITLE
Add builtin array types and functions

### PR DESCRIPTION
**Pull request by dolio**
This PR implements builtins for boxed arrays and byte arrays. Both mutable and immutable arrays are available, in both `IO` and `Scope`. Some current design notes, could be modified:

1. There's no mechanism for creating an immutable array directly. Doing so would require builtin functions for producing new arrays by modifying parts of old ones, but under the hood, this is actually just creating a mutable array, filling it, and freezing it, which you can do in Unison with the given API.
2. The API includes bounds checking, because as far as I can tell, Scheme arrays are bounds checked. This is kind of redundant, because a nicer API will have to track a separate length anyway for fast slicing. I could make the Haskell back end skip bounds checks if desired, but I'm not sure if it's possible in Scheme.
3. Currently you can only create a boxed array by specifying an initial element, because the Haskell API requires one, and I'm not sure what the exact consequences of pre-filling with a `Blackhole` closure would be (I think it would act kind of like a 'lazy' error without additional special checks, contrary to Unison's normal evaluation strategy). Not sure whether working out the details of this is better, or if I should just make a thaw/copy primops that create new arrays based on existing ones, which are sort of the one scenario where you wouldn't want to provide an up-front value.

Putting up this draft PR even though I don't think it's quite done yet, because I want to see the CI. I'm getting some weird transcript behavior locally, and want to see if it's just something with my setup.

### CODE REVIEW

**Comment by dolio** [comment]
I think this is about ready to go. I've got a bunch of wrapper functions for an array API for base once this gets merged.

**Comment by pchiusano** [comment]
@dolio can you post the type signatures you have in mind for the user facing stuff in base?

**Comment by dolio** [comment]
structural type data.Array a
      structural type data.ByteArray
      structural type mutable.Array g a
      structural type mutable.ByteArray g
      ArrayFailure.raise                 : Text -> a ->{Exception} b
      ArrayFailure.raise.doc             : Doc
      bug.impossible                     : Request Exception a -> a
      bug.impossible.doc                 : Doc
      data.Array.Raw.copyTo!.doc         : Doc
      data.Array.doc                     : Doc
      data.Array.fromList                : [a] -> data.Array a
      data.Array.fromList.doc            : Doc
      data.Array.read                    : data.Array a -> Nat ->{Exception} a
      data.Array.read.doc                : Doc
      data.Array.slice                   : Nat
                                           -> Nat
                                           -> data.Array a
                                           ->{Exception} data.Array a
      data.Array.slice.doc               : Doc
      data.Array.toList                  : data.Array a -> [a]
      data.Array.toList.doc              : Doc
      data.ByteArray.Raw.copyTo!.doc     : Doc
      data.ByteArray.fromList            : [Nat] -> data.ByteArray
      data.ByteArray.fromList.doc        : Doc
      data.ByteArray.read8               : data.ByteArray -> Nat ->{Exception} Nat
      data.ByteArray.read8.doc           : Doc
      data.ByteArray.toList              : data.ByteArray -> [Nat]
      data.ByteArray.toList.doc          : Doc
      data.ByteArray.write8              : data.ByteArray
                                           -> Nat
                                           -> Nat
                                           ->{Exception} data.ByteArray
      data.ByteArray.write8.doc          : Doc
      io.Raw.array.doc                   : Doc
      io.Raw.arrayOf.doc                 : Doc
      io.arrayOf                         : a -> Nat ->{IO} mutable.Array {IO} a
      io.arrayOf.doc                     : Doc
      io.byteArray                       : Nat ->{IO} mutable.ByteArray {IO}
      io.byteArray.doc                   : Doc
      io.byteArrayOf                     : Nat -> Nat ->{IO} mutable.ByteArray {IO}
      io.byteArrayOf.doc                 : Doc
      io.thawArray                       : data.Array a ->{IO} mutable.Array {IO} a
      io.thawArray.doc                   : Doc
      io.thawByteArray                   : data.ByteArray ->{IO} mutable.ByteArray {IO}
      io.thawByteArray.doc               : Doc
      mutable.Array.Raw.copyTo!.doc      : Doc
      mutable.Array.Raw.doc              : Doc
      mutable.Array.Raw.freeze!.doc      : Doc
      mutable.Array.Raw.freeze.doc       : Doc
      mutable.Array.doc                  : Doc
      mutable.Array.drop!                : Nat
                                           -> mutable.Array g a
                                           ->{Exception} mutable.Array g a
      mutable.Array.drop!.doc            : Doc
      mutable.Array.dropEnd!             : Nat
                                           -> mutable.Array g a
                                           ->{Exception} mutable.Array g a
      mutable.Array.dropEnd!.doc         : Doc
      mutable.Array.freeze               : mutable.Array g a ->{g} data.Array a
      mutable.Array.freeze!              : mutable.Array g a ->{g} data.Array a
      mutable.Array.freeze!.doc          : Doc
      mutable.Array.freeze.doc           : Doc
      mutable.Array.read                 : mutable.Array g a -> Nat ->{g, Exception} a
      mutable.Array.read.doc             : Doc
      mutable.Array.slice!               : Nat
                                           -> Nat
                                           -> mutable.Array g a
                                           ->{Exception} mutable.Array g a
      mutable.Array.slice!.doc           : Doc
      mutable.Array.write                : mutable.Array g a
                                           -> Nat
                                           -> a
                                           ->{g, Exception} ()
      mutable.Array.write.doc            : Doc
      mutable.ByteArray.Raw.copyTo!.doc  : Doc
      mutable.ByteArray.Raw.freeze!.doc  : Doc
      mutable.ByteArray.Raw.freeze.doc   : Doc
      mutable.ByteArray.Raw.read16be.doc : Doc
      mutable.ByteArray.Raw.read32be.doc : Doc
      mutable.ByteArray.Raw.read64be.doc : Doc
      mutable.ByteArray.doc              : Doc
      mutable.ByteArray.drop!            : Nat
                                           -> mutable.ByteArray g
                                           ->{Exception} mutable.ByteArray g
      mutable.ByteArray.drop!.doc        : Doc
      mutable.ByteArray.dropEnd!         : Nat
                                           -> mutable.ByteArray g
                                           ->{Exception} mutable.ByteArray g
      mutable.ByteArray.dropEnd!.doc     : Doc
      mutable.ByteArray.freeze!          : mutable.ByteArray g ->{g} data.ByteArray
      mutable.ByteArray.freeze!.doc      : Doc
      mutable.ByteArray.read8            : mutable.ByteArray g -> Nat ->{g, Exception} Nat
      mutable.ByteArray.read8.doc        : Doc
      mutable.ByteArray.slice!           : Nat
                                           -> Nat
                                           -> mutable.ByteArray g
                                           ->{Exception} mutable.ByteArray g
      mutable.ByteArray.slice!.doc       : Doc
      mutable.ByteArray.write8           : mutable.ByteArray g
                                           -> Nat
                                           -> Nat
                                           ->{g, Exception} ()
      mutable.ByteArray.write8.doc       : Doc
      mutable.Scope.Raw.array.doc        : Doc
      mutable.Scope.Raw.arrayOf.doc      : Doc
      mutable.Scope.arrayOf              : a
                                           -> Nat
                                           ->{mutable.Scope s} mutable.Array
                                             {mutable.Scope s} a
      mutable.Scope.arrayOf.doc          : Doc
      mutable.Scope.byteArray            : Nat
                                           ->{mutable.Scope s} mutable.ByteArray
                                             {mutable.Scope s}
      mutable.Scope.byteArray.doc        : Doc
      mutable.Scope.byteArrayOf          : Nat
                                           -> Nat
                                           ->{mutable.Scope s} mutable.ByteArray
                                             {mutable.Scope s}
      mutable.Scope.byteArrayOf.doc      : Doc
      mutable.Scope.thawArray            : data.Array a
                                           ->{mutable.Scope s} mutable.Array
                                             {mutable.Scope s} a
      mutable.Scope.thawArray.doc        : Doc
      mutable.Scope.thawByteArray        : data.ByteArray
                                           ->{mutable.Scope s} mutable.ByteArray
                                             {mutable.Scope s}
      mutable.Scope.thawByteArray.doc    : Doc

There could be much more, but it's what I've written so far. I didn't want to get too distracted writing all the array functions I could think of. There will probably be a few more that I'll need when working on the scheme stuff.

**Review by pchiusano — APPROVED** [review]
👍

**Comment by pchiusano** [comment]
@dolio can you just refresh transcripts? I think this is good to merge otherwise.

**Review by pchiusano — APPROVED** [review]

**Pull request merged**
