### PR TITLE
Add COMPLETE pragma to Reference

### PR DESCRIPTION
**Pull request by mitchellwrosen**
Removes two calls to `error`

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Huh... ok... CI failure looks like a GHC bug to me? It thinks this is now inaccessible.
```
Pattern.ConstructorP _ UnitRef 0 [] -> Just []
```

**Comment by aryairani** [comment]
Hehe, yeah :-/  see the two lines below the newly added COMPLETE pragma.

**Comment by pchiusano** [comment]
Should we close this? I’d love to have this work but @mitchellwrosen is now the second person to discover this GHC feature is buggy at least in the GHC version we are using currently.

**Comment by mitchellwrosen** [comment]
Think so :man_shrugging:

**Pull request closed without merging**
