### PR TITLE
Push docker images to github when we release

### PR DESCRIPTION
**Pull request by stew**
**Choose your PR title well:** Your pull request title is what's used to create release notes, so please make it descriptive of the change itself, which may be different from the initial motivation to make the change.

## Overview

This augments our release GitHub release workflow to push a docker image to the github registry wihch has ucm and the UI

### CODE REVIEW

**Comment by aryairani** [comment]
Awesome! But what do we use this for?

**Review by aryairani — APPROVED** [review]

**Comment by stew** [comment]
This would create another easy way for to give unison a try. They will be able to,without installing anything (besides having docker), with a single command fetch and run a docker container they can mount a local folder to that gives them ucm and the local UI.

**Comment by stew** [comment]
would also provide an easy way for someone that wanted to publish a codebase with the UI separately from share, perhaps privately

**Comment by aryairani** [comment]
LGTM. @ceedubs Go ahead and merge if it LGTY too.

**Comment by aryairani** [comment]
How does `$IMAGE_NAME` get set? Is that a Github thing?

**Comment by ChrisPenner** [comment]
Oh great! Can you add some instructions to the README plz? 😄 

Unrelated, but we should probably have an `Installing` section in the README rather than just a `building from source` section.

**Comment by stew** [comment]
OOPs, I Had left out the line to set IMAGE_NAME, that's fixed now.

@ChrisPenner I will add something to the readme, but I want to get an image pushed first to know what I'm doing first, I haven't worked with this github docker registry before.

**Pull request merged**
