### PR TITLE
Fix `request` for the case of unhandled abilities

### PR DESCRIPTION
**Pull request by jaredly**
Previously it would give an untraceable scheme error, "expected mpair, found #f".
This now just raises the ability request as an exception.

### CODE REVIEW

**Comment by dolio** [comment]
So, this just raises with the list of arguments. Maybe it should include the `r` and `t` part, too?

Also, maybe we should define a [condition type](https://www.scheme.com/tspl4/exceptions.html#./exceptions:h2) for this so it's more obvious what's going on when it happens?

**Comment by jaredly** [comment]
Ok, added the other args, and made it a condition!

**Comment by jaredly** [comment]
@dolio can we merge this too?

**Review by dolio — APPROVED** [review]
Looks good.

**Pull request merged**
