### PR TITLE
Add hie.yaml

### PR DESCRIPTION
**Pull request by mitchellwrosen**
For https://github.com/digital-asset/ghcide users

### CODE REVIEW

**Comment by aryairani** [comment]
Does it work for you?

I get:
```
22:33 ~/unison (diff.namespace)$ ghcide
ghcide version: 0.0.5 (GHC: 8.6.5)
Ghcide setup tester in /Users/arya/unison.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in /Users/arya/unison
Found 198 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading ./hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: CradleError (ExitFailure 1) ["Failed to parse result of calling stack","","* * * * * * * *","The main module to load is ambiguous. Candidates are: ","1. Package `easytest' component easytest:exe:runtests with main-is file: /Users/arya/unison/yaks/easytest/tests/Suite.hs","2. Package `unison-parser-typechecker' component unison-parser-typechecker:exe:prettyprintdemo with main-is file: /Users/arya/unison/parser-typechecker/prettyprintdemo/Main.hs","3. Package `unison-parser-typechecker' component unison-parser-typechecker:exe:tests with main-is file: /Users/arya/unison/parser-typechecker/tests/Suite.hs","4. Package `unison-parser-typechecker' component unison-parser-typechecker:exe:transcripts with main-is file: /Users/arya/unison/parser-typechecker/tests/Unison/Test/Transcripts.hs","5. Package `unison-parser-typechecker' component unison-parser-typechecker:exe:unison with main-is file: /Users/arya/unison/parser-typechecker/unison/Main.hs","You can specify which one to pick by: "," * Specifying targets to stack ghci e.g. stack ghci easytest:exe:runtests"," * Specifying what the main is e.g. stack ghci --main-is easytest:exe:runtests"," * Choosing from the candidate above [1..5]","* * * * * * * *","","<stdin>: hGetLine: end of file"]
```

and roughly the same error when autodetecting with no `hie.yaml`:
```
22:34 ~/unison (diff.namespace)$ ghcide
ghcide version: 0.0.5 (GHC: 8.6.5)
Ghcide setup tester in /Users/arya/unison.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in /Users/arya/unison
Found 198 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Implicit cradle for /Users/arya/unison
Cradle {cradleRootDir = "/Users/arya/unison", cradleOptsProg = CradleAction: stack}

Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: CradleError (ExitFailure 1) ["Failed to parse result of calling stack","","* * * * * * * *","The main module to load is ambiguous. Candidates are: ","1. Package `easytest' component easytest:exe:runtests with main-is file: /Users/arya/unison/yaks/easytest/tests/Suite.hs","2. Package `unison-parser-typechecker' component unison-parser-typechecker:exe:prettyprintdemo with main-is file: /Users/arya/unison/parser-typechecker/prettyprintdemo/Main.hs","3. Package `unison-parser-typechecker' component unison-parser-typechecker:exe:tests with main-is file: /Users/arya/unison/parser-typechecker/tests/Suite.hs","4. Package `unison-parser-typechecker' component unison-parser-typechecker:exe:transcripts with main-is file: /Users/arya/unison/parser-typechecker/tests/Unison/Test/Transcripts.hs","5. Package `unison-parser-typechecker' component unison-parser-typechecker:exe:unison with main-is file: /Users/arya/unison/parser-typechecker/unison/Main.hs","You can specify which one to pick by: "," * Specifying targets to stack ghci e.g. stack ghci easytest:exe:runtests"," * Specifying what the main is e.g. stack ghci --main-is easytest:exe:runtests"," * Choosing from the candidate above [1..5]","* * * * * * * *","","<stdin>: hGetLine: end of file"]
```

**Comment by mitchellwrosen** [comment]
I saw that too with ghcide HEAD, so I grabbed 0.0.5 from Hackage. Did you build from source?

**Comment by aryairani** [comment]
Yeah I did build from source per https://github.com/digital-asset/ghcide#with-cabal-or-stack.  Dumb question: how do you grab from stackage?  Is it just a tarball?

**Comment by mitchellwrosen** [comment]
`cabal unpack ghcide-0.0.5` (or `stack unpack`)

**Comment by aryairani** [comment]
Bleh.  That got me the source, but neither `cabal install` nor `stack install` would figure out how to get dependencies and build it.  Did you have to manually specify a resolver?

**Comment by mitchellwrosen** [comment]
I just built with `cabal build -w ghc-8.6.5` and it did find a plan. I think there are stack.yamls in that repo that should work, too.

If you didn't know, you have to use a version of ghcide that is built with the same version of ghc that you build your code with. So I don't have a `ghcide` executable on my path, but `ghcide-8.6.5` (and others) instead. Then I use `direnv` and a wrapper script to get `ghcide-8.6.5` running by vim when I open Haskell file while in the unison source dir.

**Comment by aryairani** [comment]
So finally, does adding this file actually do something?  (Seems like ghcide detects a stack project regardless.)

**Comment by mitchellwrosen** [comment]
Guess not if `ghcide` can infer it!

**Comment by aryairani** [comment]
The `hie-bios` docs do "strongly recommend" explicitly configuring the project with a `hie.yaml`, but I don't wanna add any tool-specific files that don't pay for themselves, so I think we should close this for now.

That said, if there was some future explicit hie configuration, or cabal/stack refactoring that _would_ speed up or improve the Haskell development experience (fast recompilation, jump to actual definition, show type of expression/pattern, automatic imports), I would super strongly support it.

**Pull request closed without merging**
