### PR TITLE
Key value store

### PR DESCRIPTION
**Pull request by sfultong**
@pchiusano here's a start. Let me know if I'm on the right track.

### CODE REVIEW

**Comment by pchiusano** [comment]
Taking a look

**Comment by pchiusano** [comment]
Hey I have some more detailed comments on this, but won't be able to write them up until tonight. The big thing that is missing is the ability to serialize stuff other than text. For the keys, you should compute the hash of the term (probably after WHNF'ing), and for the values, use the binary serialization that you get if you import Unison.Term.Extra. I can elaborate more later if that doesn't make sense.

**Comment by pchiusano** [comment]
Okay, so first, I would separate out the key value store into its own module. It will just store (and be keyed by) arbitrary bytestrings:

```Haskell
module Unison.Runtime.KeyValueStore where

import Data.ByteString (ByteString)

data Db = ... -- probably just an AcidState (Map ByteString ByteString) or something

empty :: FilePath -> IO Db
empty path = ...

load :: FilePath -> IO Db
load path = ...

insert :: ByteString -> ByteString -> Db -> IO ()
insert k v db = ...

delete :: ByteString -> Db -> IO ()
delete k db = ...

lookup :: ByteString -> Db -> IO (Maybe ByteString)
lookup k db = ...

-- | Find next key in the Db whose key is greater than the provided key
nextKey :: ByteString -> Db -> IO (Maybe ByteString)
nextKey k db = ...
```

This module will be implemented with acid state or whatever, but that fact won't be exposed to users. Makes it easy to test independently of Unison.

Now, this module will get used to store Unison terms in the following way. To store the entry `(k,v)`, we'll compute the hash of `k` and use that as the key passed to `KeyValueStore.insert`, and for the value we'll do a binary serialization of the entry `(k,v)`.

Here's how you can compute the hash of a `Term`:

```Haskell
import Unison.Term as Term
import Unison.Reference (Reference, Derived)
import qualified Unison.ABT as ABT

hash :: (Var v) => Term.Term v -> Reference
hash (Term.Ref' r) = r
hash t = Derived (ABT.hash t)
```

That gives you back a `Reference`, which you can serialize to use for your key.

To serialize a Unison term (or anything else, like `Reference`), you should be able to use `Data.Bytes.Serialize`:

```Haskell
import Data.Bytes.Serialize (serialize)
import Unison.Term.Extra -- Serial instances
import Unison.ABT.Extra -- Serial instances
import Unison.Reference.Extra -- ..
-- might need some other imports, and might need to put an instance for `Serial View.DFO` in `Unison.View.Extra`
```

If you call `serialize` on a Unison term (once you have all the instances you need), you'll notice it returns a `Put` which is polymorphic. I would resolve that to the [cereal package's `Put`](https://hackage.haskell.org/package/cereal) using a type annotation, then convert that `Put` to a strict `ByteString` using [`runPutS`](https://hackage.haskell.org/package/bytes-0.15.2/docs/Data-Bytes-Put.html).

Since that is a lot of hoops to jump through, I would not mind having a single module, `Unison.SerializationAndHashing` which has all the imports needed and exposes just the serialization and hashing functions. Or LMK if you have other idea for how to clean this up and make it more convenient.

Anyway now you have a way of hashing arbitrary Unison terms, and a way of serializing arbitrary Unison terms. Just use this in conjunction with the `KeyValueStore` implementation.

LMK if that makes sense or if you get stuck on anything!

Moving the builtins to their own module seems sensible to me.

**Comment by pchiusano** [comment]
Hey @sfultong can you merge with `topic/distributed` and try to stay in sync with that? It will make it a lot easier to merge your branch when it's ready.

**Comment by sfultong** [comment]
Sure thing.

**Pull request closed without merging**
