### PR TITLE
stack.yaml: update to final lts-18.28 snapshot

### PR DESCRIPTION
**Pull request by juhp**
lts-18.28 is the last minor release of LTS 18

I tested this successfully building M3 and also current HEAD (863d989).
stack exec tests and stack test also pass.

### CODE REVIEW

**Review by ceedubs — APPROVED** [review]
Thanks @juhp! LGTM

**Comment by ceedubs** [comment]
The Windows build failed (at least twice in a row) with the following:

```
C:\Users\runneradmin\AppData\Local\Temp\stack-ff926c16fac8c49d\unix-time-0.4.7\.stack-work\dist\274b403a\setup: removeDirectoryRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:RemoveDirectory "\\\\?\\C:\\Users\\runneradmin\\AppData\\Local\\Temp\\stack-ff926c16fac8c49d\\unix-time-0.4.7\\.stack-work\\dist\\274b403a\\setup": unsatisfied constraints (The directory is not empty.)
```

@aryairani or @ChrisPenner does this mean anything to you?

**Comment by ChrisPenner** [comment]
@ceedubs  ugh, yeah that's from race-conditions within the Windows file APIs unfortunately 😞 

The likelihood of crashing is proportional to the number of new packages, so it makes sense that updating the LTS would run into issues. Let's keep mashing the re-build button and hopefully it'll get through eventually...

If it doesn't, I can temporarily edit the windows build to retry until it succeeds within a single job so that the cache gets warmed up, once one job succeeds then subsequent jobs will have a build cache and should work better 👍🏼

**Comment by ChrisPenner** [comment]
Okay I added some retry logic on windows, we'll see if that helps 🤞🏼

**Pull request merged**
